// Test Lab — each station's method and every number on the page, next to its public source.
// The 參數依據 panel reads this file, and make_refs.py copies it into test/README.md.
window.TEST_SOURCES = {
  intro: '這是示意模型：六站的量測原理是真的，板子、缺陷和數字是簡化過的例子。下面列出每一站在量什麼、這一頁用的值、公開資料裡的數字和出處。所有來源都是公開文件；設備規格多半是廠商型錄上的最佳值，不是任何公司的實際規格或流程。',
  steps: [
    { zh: '光學檢查（AOI）', d: '相機拍下零件，跟標準板比對亮度和顏色：少件、錯件、極性、偏移、連錫都看得出來；2D 量不到高度，3D 機型用結構光量高度。公開機型的解析度約 10–20 μm／像素，一張約 30 × 30 mm，每秒檢查 7–26 cm²。', r: [1, 2] },
    { zh: '飛針測試', d: '探針自己移到測點，不用做專用治具，適合少量多樣和試產的板子。電阻用定電流量，電容、電感用交流定電壓量，二極體量順向電壓；被量的電阻旁邊有並聯路徑時，用「護衛（guard）」把旁邊的電流引開。公開機型每一步 0.02–0.06 秒。', r: [3, 4, 5, 6, 8] },
    { zh: '網路測試', d: '每一條網路量導通，網路之間量絕緣。IPC-9252A 的 C 級：導通 ≤ 10 Ω、絕緣 ≥ 10 MΩ；自動設備至少加 40 V，很多測試廠用 100 V；太空與軍用的 3/A 級例子是 250 V、≥ 100 MΩ。細間距的飛針機可以打到幾十微米間距的接點，用四線量測抓導通孔斷開造成的微小電阻上升。', r: [9, 10, 11, 12, 13, 14] },
    { zh: 'X 光檢查', d: '錫對 X 光的衰減遠大於銅和板材，所以錫球、橋接、空洞的對比很強。正上方拍看不出空洞在錫球的哪一層；空洞超過錫球影像面積 25 % 判為不良。枕頭效應（錫球和錫膏各自熔化卻沒有融合）建議斜 55–70° 拍，而且 X 光也不保證每顆都抓得到。', r: [18, 19, 24, 25, 26, 27] },
    { zh: '平整度量測', d: '影像量測儀在表面一點一點自動對焦，量出每點高度，用最小二乘法找出平面、扣掉傾斜，再取最高點和最低點的差。標準的平整度定義是「夾住表面的兩個平行面」，最小二乘法最常用，算出來會比它略大。', r: [28, 29, 30] },
    { zh: '上機診斷', d: '板子裝上測試機跑板子檢查程式：一顆顆切換繼電器、對通道強迫電流量電壓、強迫小電流量電壓和時間算出電容（C = I·Δt / ΔV）。查誤判時要逐一比對板子、彈簧針塔和測試機本身。探針卡可以壓在短路晶圓或驗證晶圓上，把探針端的迴路接回來。', r: [33, 34, 35, 36, 37, 38] },
  ],
  params: [
    { p: '相機解析度', sim: '5–40 μm／像素，預設 15', real: '公開 3D AOI：15 μm，4 MP 一張 30 × 30.72 mm；其他機型 10、20 μm', r: [1, 2] },
    { p: 'AOI 速度', sim: '15 μm 時每秒 15 cm²，隨像素面積變（示意）', real: '公開機型每秒 7.1–26.2 cm²，最快 52.3 cm²', r: [2] },
    { p: '極性標記', sim: '0.15 mm，至少 4 個像素才判得準（示意）', real: 'AOI 的檢查項目包含極性、少件、錯件、偏移、連錫；2D 量不到高度', r: [1, 2] },
    { p: '飛針速度', sim: '每步 0.05 秒 × 400 步', real: '公開機型每步 0.02–0.06 秒（2.5 mm 移動）；另一款最快 0.025 秒', r: [3, 5] },
    { p: '飛針定位', sim: '—', real: '重複精度 ±25 μm、最小接點 50 μm、最小間距 150 μm（高精度模式）', r: [4] },
    { p: '護衛', sim: '三線護衛：旁邊兩顆 4.7 kΩ，護衛探針 1 Ω', real: '沒護衛時電流分到並聯路徑；護衛點接地後，旁邊那顆兩端幾乎同電位、沒有電流', r: [6] },
    { p: '量測誤差', sim: '1σ 0.5 %（示意）；好的電阻 ±1 %', real: '公開的針床式 ICT：有護衛（比 1000:1）時 10 kΩ 為 ±2.5 %', r: [7] },
    { p: '電阻容許誤差', sim: '±1–15 %，預設 ±5 %', real: '判定上下限可以自己設（公開機型 −999.9 % 到 +999.9 %）', r: [3] },
    { p: '繼電器', sim: '飛針這一站只量線圈和二極體', real: '有些專門測負載板的飛針機，也能量繼電器切換時間和整條通道的導通', r: [41] },
    { p: '去耦電容', sim: '52 顆並聯，少 1 顆總電容只少 1.9 %', real: '並聯在同一條電源上的電容，在電路上量到的是總和；少件要靠 AOI 看', r: [1, 6] },
    { p: '導通上限', sim: '10 Ω', real: 'IPC-9252A：A 級 100 Ω、B 級 50 Ω、C 級 10 Ω', r: [9, 10] },
    { p: '絕緣下限', sim: '100 MΩ', real: 'IPC-9252A：A 級 500 kΩ、B 級 2 MΩ、C 級 10 MΩ；3/A 級例子 100 MΩ @ 250 V', r: [9] },
    { p: '絕緣測試電壓', sim: '5–250 V，預設 100 V', real: '自動設備至少 40 V，人工至少 200 V；很多測試廠用 100 V；CAF 試驗也用 100 V 量絕緣', r: [9, 42] },
    { p: '有殘留物的漏電', sim: '低電壓約 5 GΩ，30 V 以上開始漏，80 V 時跌破 100 MΩ（示意）', real: '探針卡 FR-4 走線之間 > 100 MΩ（5 V 下 < 100 nA）；探針卡進料規格例子：針與針之間漏電 < 100 nA', r: [39, 40] },
    { p: '量測上限', sim: '100 GΩ', real: '公開的細間距飛針機：絕緣 1 kΩ–100 GΩ', r: [11, 12, 13] },
    { p: '細間距', sim: '—', real: '公開的細間距飛針機：最小間距 34–45 μm、接點 4–15 μm（特定探針）', r: [11, 13] },
    { p: '四線量測', sim: '兩線會多算兩個接觸電阻', real: '量測導線本身 1–10 mΩ，兩線量測在 10–100 Ω 以下就不可靠；四線把送電流和量電壓分開，接觸壓降不算進去', r: [14] },
    { p: '探針接觸電阻', sim: '每點 10–150 mΩ', real: '彈簧探針 10–150 mΩ，最常見 20 mΩ', r: [15] },
    { p: '電源路徑', sim: '4.0 mΩ；少四分之一的孔變 5.2 mΩ；上下限 ±10 %', real: '細間距飛針機用四線量測抓「導通孔斷開造成的電阻上升」；導通孔可靠度試驗以電阻變化 10 %（IST）或 5 %（回焊模擬）判失效', r: [11, 12, 16, 17] },
    { p: 'X 光管電壓', sim: '50–130 kV，預設 90 kV', real: '公開設備 30–160 kV', r: [20, 21] },
    { p: '衰減係數', sim: '錫 60 keV 6.56 cm²/g、銅 1.59；錫球密度 7.49 g/cm³；板材用水和玻璃的平均代替', real: '0.6 mm 的錫在 60 keV 只透過約 5.6 %，35 μm 的銅透過約 95 %', r: [18, 19, 22, 23] },
    { p: 'X 光光譜', sim: '鎢靶連續光譜（Kramers 定律），穿過越多材料越「硬」', real: '管電壓是最高能量，平均能量低很多；穿過材料後低能量先被吸收', r: [18] },
    { p: '空洞上限', sim: '25 %（錫球影像面積）', real: 'IPC-A-610D/E：超過 25 % 為不良；IPC-7095A 依等級和位置 4–36 %；正上方拍無法判斷位置時用最嚴的', r: [24] },
    { p: '斜拍角度', sim: '0–70°；55° 以上才看得出枕頭效應', real: '建議 55–70° 斜拍、360° 旋轉；設備最大 70–75°；X 光判枕頭效應不完全可靠', r: [25, 26, 27, 20, 21] },
    { p: '偵測器', sim: '每秒 30 張，可疊加 1–32 張', real: '公開設備：6.5 MP、每秒 30 張', r: [20] },
    { p: '對焦點數', sim: '2 × 2 到 15 × 15 點，每點 1 秒（示意）', real: '每點時間依機型和量測程式而定', r: [] },
    { p: '高度量測誤差', sim: '每點 1 μm', real: '雷射對焦重複性 2σ ≤ 0.5 μm；Z 軸誤差 1.2 + 5L/1000 μm（L 單位 mm）', r: [28] },
    { p: '平整度定義', sim: '最小二乘平面的峰谷值', real: '標準定義是最小區域（兩平行面）；最小二乘法最常用、結果略大', r: [29] },
    { p: '平整度上限', sim: '38 μm', real: '2002 年 MLO 例子：整片 ≤ 0.0015 吋（38 μm）；探針卡平面度例子 < 30 μm，進料 ±50 μm', r: [30, 31, 40] },
    { p: '探針卡分析儀', sim: '沒有模擬', real: '分析儀用影像量探針位置，也量平面度、接觸電阻、漏電和配線', r: [32, 40] },
    { p: '上機診斷', sim: '每個通道 1 mA、繼電器逐顆切換、電源電容 ±10 %', real: '板子檢查程式：切換繼電器、強迫電流量電壓；電容用 C = I·Δt / ΔV 算；在批量開始、中間、結束都跑', r: [33] },
    { p: 'PMU 量程', sim: '1 mA', real: '公開的量測單元晶片：±5 μA、±20 μA、±200 μA、±2 mA（外接可到 ±80 mA）；強迫電流、量電壓', r: [35, 36] },
    { p: '同型號、同配置', sim: '12 個儀器槽要對上這片板子要的儀器', real: '診斷程式寫在該型測試機的程式裡、用它自己的儀器；查誤判時要逐一比對板子、彈簧針塔、測試機。「要用跟客戶一樣的機型和配置」是本頁的歸納', r: [33, 34] },
    { p: '探針端接回', sim: '—', real: '探針卡可以放在驗證晶圓上，或用全部接地的短路探針卡，把迴路接回來找開路、短路', r: [37, 38] },
    { p: 'DIS', sim: '—', real: 'DIS Tech 官網：首批板子良率超過 90 %', r: [43] },
  ],
  left: '沒有模擬的部分：功能測試（實際跑晶片的測試程式）、高頻的 TDR 和插入損耗、熱循環後才出現的裂縫（微孔裂縫冷卻後可能又接上，室溫量不到）、X 光的電腦斷層與分層攝影、探針卡分析儀（量探針高度、位置、接觸電阻、漏電）、清潔與外觀檢查。每一站的時間是示意值；設備規格引用的是公開型錄上的最佳值。',
  refs: [
    { t: 'Omron VT-S730 3D AOI (distributor page) — resolution, field of view, inspection items', u: 'https://www.etek-europe.com/divisions/imaging-ndt-x-ray-ct-systems/omron/3d-aoi-systems/omron-vt-s730/' },
    { t: 'Koh Young — What is automated optical inspection', u: 'https://kohyoungamerica.com/what-is-automated-optical-inspection/' },
    { t: 'Takaya APT-1600FD catalogue (2022, distributor copy)', u: 'https://accelonix.nl/wp-content/uploads/APT-1600FD-Catalog_2022.4.19_ENU.pdf' },
    { t: 'Takaya APT-2600FD flying-probe tester', u: 'https://www.takaya-itochu.com/products/apt-2600fd/' },
    { t: 'Hioki FA1240 populated-board flying-probe tester', u: 'https://www.hioki.com/us-en/products/bare-board/populated-board/id_6638' },
    { t: 'Suto (Teradyne) — Principles of Analog In-Circuit Testing, 2012', u: 'https://smtnet.com/library/files/upload/PrinciplesofAnalogInCircuitTesting.pdf' },
    { t: 'Keysight i3070 Series 6 data sheet (reseller copy)', u: 'https://docs.alltest.net/manual/Alltest-Agilent-Keysight-E9902G-Datasheet-29440-.pdf' },
    { t: 'Wikipedia — Flying probe', u: 'https://en.wikipedia.org/wiki/Flying_probe' },
    { t: 'Kolmodin (Gardien) — IPC 9252A Electrical Test Considerations & Military Specifications versus Electrical Test', u: 'https://www.smtnet.com/library/files/upload/IPC-9252A-considerations.pdf' },
    { t: 'Meraw & Kolmodin (Gardien) — Electrical Test Conditions & Considerations', u: 'https://www.electronics.org/system/files/technical_resource/E2&S26_01.pdf' },
    { t: 'Hioki FA1817 flying-probe tester (fine pitch, 4-wire open-via detection)', u: 'https://www.hioki.com/us-en/products/bare-board/flying-probe/id_6719' },
    { t: 'Hioki FA1283 flying-probe tester (4-terminal low resistance for open vias)', u: 'https://www.hioki.com/global/products/bare-board/flying-probe/id_6604' },
    { t: 'Hioki FA1815-20 flying-probe tester', u: 'https://www.hioki.com/global/products/bare-board/flying-probe/id_1266709' },
    { t: 'Keithley — Low Level Measurements Handbook, chapter 3 (mirror copy)', u: 'https://docs.ampnuts.ru/eevblog.docs/Keithley/Ch3_LowLevMsHandbk.pdf' },
    { t: 'Feinmetall ICT/FCT spring-probe catalogue (distributor copy)', u: 'https://www.imtts.cz/wp-content/uploads/2021/08/Feinmetall-katalog-ICT-FCT.pdf' },
    { t: 'IPC-TM-650 2.6.26A — DC current induced thermal cycling (IST)', u: 'https://www.electronics.org/sites/default/files/test_methods_docs/2-6_2-6-26a.pdf' },
    { t: 'ATCO — D-coupon testing per IPC-TM-650 2.6.27 for microvia reliability', u: 'https://www.atco-us.com/2023/12/26/ipc-d-coupon-testing-per-ipc-tm-650-2-6-27-for-microvia-reliability-verification/' },
    { t: 'NIST X-ray mass attenuation coefficients — tin (SRD 126)', u: 'https://physics.nist.gov/PhysRefData/XrayMassCoef/ElemTab/z50.html' },
    { t: 'NIST X-ray mass attenuation coefficients — copper', u: 'https://physics.nist.gov/PhysRefData/XrayMassCoef/ElemTab/z29.html' },
    { t: 'Nordson Quadra 7 Pro X-ray data sheet (distributor copy)', u: 'https://amtest-group.com/wp-content/uploads/2023/04/Quadra-7-Pro-Datasheet-Nordson-TI_XRAY_M.pdf' },
    { t: 'Nikon XT V 160 electronics X-ray system (distributor page)', u: 'https://www.exceltechnologies.com/measuring/x-ray-and-ct-systems/nikon-xt-v-160-electronics-x-ray-system' },
    { t: 'MG Chemicals — SAC305 solder technical data sheet', u: 'https://www.mgchemicals.com/downloads/tds/tds-4925-4926.pdf' },
    { t: 'NIST X-ray mass attenuation coefficients — water and borosilicate glass (laminate stand-ins)', u: 'https://physics.nist.gov/PhysRefData/XrayMassCoef/ComTab/pyrex.html' },
    { t: 'Balsavar (Agilent) — X-ray Inspection of Voids in BGA Joints with Respect to the IPC-7095A Specification, IPC APEX 2006', u: 'https://www.electronics.org/system/files/technical_resource/E16&S16-02.pdf' },
    { t: 'Feng et al. (Flextronics, Dage) — Modern 2D X-ray Tackles BGA Defects, I-Connect007', u: 'https://iconnect007.com/index.php/article/44225/modern-2d-xndashray-tackles-bga-defects/44228' },
    { t: 'Bruno & Gustafson (Ericsson) — Head-on-Pillow Defect Detection: X-ray Inspection Limitations', u: 'https://smtnet.com/library/files/upload/S03-2.pdf' },
    { t: 'Castellanos et al. (Flextronics) — Head in Pillow X-ray Inspection at Flextronics', u: 'https://smtnet.com/library/files/upload/head-in-pillow-inspection-flextronics.pdf' },
    { t: 'Nikon NEXIV VMZ-S video measuring system — specifications', u: 'https://nikon.com/products/industrial-metrology/lineup/nexiv/vmzr_series/vmzr_6555/spec.htm' },
    { t: 'Srinivasan, Shakarji & Morse (NIST) — On the Enduring Appeal of Least-squares Fitting in Computational Coordinate Metrology', u: 'https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=907559' },
    { t: 'Fulton & Pardee (Wentworth) — Using MLOs to Build Vertical Technology Space Transformers, SWTW 2002', u: 'https://www.swtest.org/swtw_library/2002proc/PDF/S04_03.pdf' },
    { t: 'Wolfe et al. (TI, MJC) — 50um In-line Pitch Vertical Probe Card, SWTW 2009', u: 'https://www.swtest.org/swtw_library/2009proc/PDF/S08_02_Wolfe_SWTW2009.pdf' },
    { t: 'Schwartz — Measurement Repeatability Key to Probe-Card Metrology, 1998', u: 'https://www.electronicdesign.com/home/article/21200247/measurement-repeatability-key-to-probe-card-metrology' },
    { t: 'Martinez, Perez & Dela Cruz (TI Philippines) — Finding the Sweet Spot: Non-Genuine Load Board Check Fails, ASEMEP', u: 'https://seipi.org.ph/wp-content/uploads/2025/05/FINDING-THESWEET-SPOT-A-DEEP-DIVE-ANALYSIS-ON-NON-GENUINELOAD-BOARD-CHECK-FAILS.pdf' },
    { t: 'Teradyne — software services (DIB Diagnostics, DIB Health Monitor)', u: 'https://www.teradyne.com/services/teradyne-software-services/' },
    { t: 'Jung, Kim & Kim — Cost Effective Test Methodology Using PMU for ATE Systems, VLSICS 2014', u: 'https://aircconline.com/vlsics/V5N1/5114vlsi02.pdf' },
    { t: 'Analog Devices AD5522 — quad parametric measurement unit data sheet', u: 'https://www.analog.com/media/en/technical-documentation/data-sheets/ad5522.pdf' },
    { t: 'US6911814B2 (FormFactor) — probe card verification wafer', u: 'https://patents.google.com/patent/US6911814B2/en' },
    { t: 'US11821919B2 (Winbond) — short-circuit probe card for locating tester faults', u: 'https://patents.google.com/patent/US11821919B2/en' },
    { t: 'Tektronix — Probe Card Tutorial', u: 'https://www.tek.com/en/documents/whitepaper/probe-card-tutorial' },
    { t: 'Mair & Copeland (TI) — probe-card incoming checks, SWTW 2015', u: 'https://www.swtest.org/swtw_library/2015proc/PDF/S08_01_Mair_SWTW2015R.pdf' },
    { t: 'Acculogic — load board test (flying prober for load boards)', u: 'https://www.acculogic.com/products/load-board-test' },
    { t: 'IPC-TM-650 2.6.25C — conductive anodic filament (CAF) test', u: 'https://www.electronics.org/sites/default/files/test_methods_docs/2.6.25C.pdf' },
    { t: 'DIS Tech — Our technologies', u: 'https://www.dis.tech/technologies-and-products/our-technologies' },
  ],
};
