"""Voice clips for the game: each level's briefing and lesson, plus the four verdicts.

  python game/make_voice.py          # synthesize what is missing, write game/voice.js
  python game/make_voice.py --dry    # only print what would be spoken

The words come from game/content.js, so the voice always matches the text on screen.
Uses the same Gemini TTS voice and whisper check as ../narration.py.
"""
import json, os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
sys.stdout.reconfigure(encoding="utf-8")
import narration as N

OUT = os.path.join(HERE, "voice")


def spoken(t):
    """Screen text -> what the voice should say: units and digits spelled out."""
    t = re.sub(r"(\d+)\s*[–~～]\s*(\d+)", r"\1到\2", t)
    t = t.replace("μm", "微米").replace("°C", "度").replace("kgf", "公斤").replace("AI ", "AI")
    t = re.sub(r"(\d+(?:\.\d+)?)\s*%", r"百分之\1", t)
    t = re.sub(r"(\d)\s*A(?![A-Za-z])", r"\1安培", t)
    t = re.sub(r"(?<![\d.])2\s*g\b", "兩克", t)
    t = re.sub(r"(\d)\s*g(?![A-Za-z])", r"\1克", t)
    t = re.sub(r"\d+(?:\.\d+)?", N.cn_number, t)
    return re.sub(r"(?<=[一-鿿])\s+(?=[一-鿿])", "", t)


def lines():
    js = "import('./content.js').then(m => process.stdout.write(JSON.stringify({T: m.TEXT, R: m.RANK})))"
    C = json.loads(subprocess.check_output(["node", "-e", js], cwd=HERE).decode("utf-8"))
    ids = json.loads(subprocess.check_output(
        ["node", "-e", "import('./model.js').then(m => process.stdout.write(JSON.stringify(m.LEVELS.map(l => [l.n, l.id]))))"], cwd=HERE).decode("utf-8"))
    out = []
    for n, lid in ids:
        out.append((f"l{n}", C["T"][lid]["brief"]))
        out.append((f"les{n}", C["T"][lid]["lesson"]))
    out += [(f"res{i}", r + "。") for i, r in enumerate(C["R"])]
    return out


def main():
    os.makedirs(OUT, exist_ok=True)
    items = [dict(id=i, zh=spoken(t)) for i, t in lines()]
    for it in items:
        it["file"] = os.path.join(OUT, f"{it['id']}_{N.key(it['zh'])}.mp3")
    if "--dry" in sys.argv:
        for it in items:
            print(it["id"], it["zh"])
        return
    todo = [it for it in items if not os.path.exists(it["file"])]
    print(f"{len(items)} clips, {len(todo)} to synthesize", flush=True)
    if todo:
        N.synth_gemini(todo)
    keep = {os.path.basename(it["file"]) for it in items}
    for f in os.listdir(OUT):                       # drop clips whose text has changed
        if f not in keep:
            os.remove(os.path.join(OUT, f))
    voice = {it["id"]: dict(src=os.path.basename(it["file"]), d=round(N.duration(it["file"]), 2)) for it in items}
    with open(os.path.join(HERE, "voice.js"), "w", encoding="utf-8", newline="\n") as f:
        f.write("// generated by make_voice.py — clip file and length in seconds\nwindow.VOICE = " + json.dumps(voice, ensure_ascii=False, indent=1) + ";\n")
    print(f"voice.js: {len(voice)} clips, {sum(v['d'] for v in voice.values()):.0f} s")


if __name__ == "__main__":
    main()
