// generated by make_voice.py — clip file and length in seconds
window.VOICE = {
 "l1": {
  "src": "l1_290eddc621.mp3",
  "d": 11.43
 },
 "les1": {
  "src": "les1_f97bacbf91.mp3",
  "d": 14.9
 },
 "l2": {
  "src": "l2_a234b8dbb3.mp3",
  "d": 9.38
 },
 "les2": {
  "src": "les2_e30d8f7448.mp3",
  "d": 14.52
 },
 "l3": {
  "src": "l3_4aca5c9ab1.mp3",
  "d": 14.97
 },
 "les3": {
  "src": "les3_819950235d.mp3",
  "d": 12.15
 },
 "l4": {
  "src": "l4_dbb9ae9bf1.mp3",
  "d": 15.09
 },
 "les4": {
  "src": "les4_41263ae2fe.mp3",
  "d": 12.3
 },
 "l5": {
  "src": "l5_340059c8b0.mp3",
  "d": 16.23
 },
 "les5": {
  "src": "les5_e9f11bbf2c.mp3",
  "d": 12.39
 },
 "l6": {
  "src": "l6_9e15a55f5b.mp3",
  "d": 15.9
 },
 "les6": {
  "src": "les6_c45d4315e3.mp3",
  "d": 10.49
 },
 "l7": {
  "src": "l7_05212ef392.mp3",
  "d": 17.95
 },
 "les7": {
  "src": "les7_cde3fd6ecd.mp3",
  "d": 22.29
 },
 "l8": {
  "src": "l8_80995ff446.mp3",
  "d": 21.05
 },
 "les8": {
  "src": "les8_f1ecd3ba20.mp3",
  "d": 21.36
 },
 "res0": {
  "src": "res0_360cfa78e1.mp3",
  "d": 1.88
 },
 "res1": {
  "src": "res1_5973dcc8bd.mp3",
  "d": 1.21
 },
 "res2": {
  "src": "res2_acde46f74d.mp3",
  "d": 1.77
 },
 "res3": {
  "src": "res3_c8bbc5c93a.mp3",
  "d": 1.99
 }
};
