// Where the simulator's numbers come from. index.html renders this in the 參數依據 panel,
// and make_refs.py copies it into README.md. Reference numbers are 1-based positions in `refs`.
window.SOURCES = {
  intro: '這是示意模型：幾何尺寸有放大，物理是簡化公式。下面列出每個步驟和可調參數用的數值、公開資料裡的典型範圍，以及出處。所有來源都是公開文件；數字是業界通用量級，不是任何產品或專案的規格。',
  steps: [
    { zh: '上片與對位（模擬器省略）', d: '晶圓從晶舟載入、做晶圓對位，再用上看／下看相機把探針對準鋁墊（PTPA）。', r: [3, 10] },
    { zh: '步進 INDEX', d: '載台在 XY 方向移到下一組晶粒。含 Z 軸上下，典型步進時間約 0.7 秒。', r: [2, 7] },
    { zh: '上升接觸 Z-UP', d: '載台抬升，直到探針第一次碰到鋁墊（first contact）。', r: [3, 10] },
    { zh: '過驅 OVERDRIVE', d: '接觸後再往上壓一段距離，補償探針高低差，並讓針尖刮破鋁墊表面的氧化層。', r: [3, 5, 20] },
    { zh: '電性測試 TEST', d: '訊號由測試機經彈簧針、主板、MLO 載板、探針到晶粒。測試時間通常遠大於移動時間。', r: [31, 34, 7] },
    { zh: '離開 RELEASE', d: '載台下降，晶粒依結果分 bin 記進晶圓圖，再換下一組。', r: [30, 2] },
    { zh: '清針與針痕檢查', d: '每隔數十到上百次下針，用清針片清掉針尖的沾黏物，並定期檢查針痕（PMI）。模擬器只做了計數和接觸電阻漂移。', r: [29, 30, 11] },
    { zh: '溫度（模擬器省略）', d: '量產常在 −55 °C 到 150–200 °C 之間測試，探針卡和機台都需要預熱。', r: [37] },
  ],
  params: [
    { p: '過驅量 Overdrive', sim: '0–200 μm，預設 75 μm；標示的常用範圍 50–100 μm', real: '懸臂針 25–100 μm，常用 50–75 μm；垂直針在鋁墊上約 75 μm；凸塊／銅柱可到 150–200 μm', r: [3, 4, 5, 17, 15] },
    { p: '懸臂針針壓', sim: '0.06 gf/μm，75 μm 時約 4.5 gf（線性）', real: '鎢／鎢錸針 1.0–2.5 gf/mil，也就是 0.04–0.10 gf/μm', r: [4, 19] },
    { p: '垂直針針壓', sim: 'Cobra 型挫曲針：75 μm 時約 4.5 gf，之後趨平', real: 'Cobra／挫曲針在 75 μm 約 4.5–6.5 g；新一代 MEMS 垂直針只有 1–3 g', r: [12, 13, 14, 21, 24] },
    { p: '針痕長度', sim: '懸臂 ≈ 0.22×OD＋6 μm（75 μm 時約 23 μm）；垂直 ≈ 0.05×OD＋10 μm（約 14 μm）', real: '懸臂 15–25 μm（文獻範圍 13–38 μm）；垂直 11–18 μm，主要是針尖本身的大小', r: [20, 18, 16, 15, 13] },
    { p: '鋁墊尺寸', sim: '60 μm', real: '打線鋁墊約 55–90 μm 見方', r: [4, 13, 16] },
    { p: '接觸電阻 CRES', sim: '壓穩後約 0.1–0.3 Ω；過驅量太小時偏高', real: '穩定值 < 0.25–0.3 Ω，規格常訂 < 1 Ω；過驅量超過約 25–60 μm 才會穩定', r: [13, 17, 18, 6] },
    { p: '過載上限（示意）', sim: '懸臂 125 μm、垂直 170 μm', real: '懸臂針過驅量一般不超過 127 μm，否則針尖會損傷；挫曲針常用到 150 μm；MEMS 垂直針多限制在 100 μm。公開資料沒有實測的塑性變形門檻', r: [22, 16, 14, 15] },
    { p: '平整度', sim: '翹曲 0–100 μm，超過 25 μm 標為超標', real: '探針平整度規格約 ≤25 μm 或 ±10–20 μm；受力或升溫後整張卡可再變形數十 μm', r: [4, 23, 17, 26] },
    { p: '探針尺寸與材質', sim: '垂直針長約 5 mm；懸臂針為鎢錸', real: 'Cobra／挫曲針長 4.3–6.4 mm、線徑 25–64 μm；鎢錸是最常見的懸臂針材料', r: [13, 4, 22] },
    { p: 'Z 分離距離', sim: '200 μm', real: '公開規格為 200–300 μm，量產機台由 recipe 設定', r: [8, 9] },
    { p: '每次移動時間', sim: '0.7 秒（步進 0.35＋上升 0.15＋過驅 0.08＋離開 0.12）', real: '典型步進時間 0.7 秒；工程機台 0.75–1.5 秒', r: [7, 8] },
    { p: '每次測試時間', sim: '0.2–60 秒，預設 1.5 秒（約 27 次／分）；另有 10×、60× 快轉', real: '依產品從數秒到數分鐘，公開例子有 5 秒、10 秒、180 秒', r: [1, 28, 7] },
    { p: '同測顆數', sim: '每次下針 4 顆', real: '大晶粒的 AI 處理器 x8–x16；一般邏輯可達 128 顆以上；DRAM 可以一次測完整片', r: [27, 28, 1] },
    { p: '清針間隔', sim: '每 100 次下針；接觸電阻隨次數緩慢升高（示意）', real: '常見做法是每 50–100 次清一次，實際間隔依產品調整', r: [29, 30] },
    { p: '探針數與總針壓', sim: '這張卡 224 針', real: 'HPC 卡約 2 萬針、每針約 2 g；最新的卡超過 10 萬針，總針壓 170–280 kgf，接近載台約 300 kgf 的上限', r: [24, 25, 26] },
    { p: '晶圓與晶粒', sim: '300 mm 晶圓、約 18 mm 晶粒、157 顆', real: '18 mm 晶粒、邊緣排除 3 mm 時約 170–180 顆毛晶粒（依標準公式推算）', r: [] },
    { p: '主板層數', sim: '標示「數十層」', real: '公開的探針卡 PCB 例子為 42–76 層、厚 2.7–9.6 mm', r: [33] },
    { p: '探針卡結構與 DIS', sim: '彈簧針塔 → 補強板 → 主板 → MLO 載板 → 探針頭 → 晶圓', real: '主板、（中介層）、空間轉換板、探針頭的組成與專利描述一致；補強板是機構件，不在訊號路徑上。DIS Tech 在 2024 年 5 月由 Technoprobe 自 Teradyne 收購', r: [31, 32, 34, 35, 36] },
  ],
  left: '模擬器沒有做的部分：溫度、上片與對位、針痕檢查、探針磨耗與壽命（公開資料為 100 萬次以上）、電流承載能力，以及整張卡受力後的變形（高針數卡上，實際過驅量只有設定值的一部分）。',
  refs: [
    { t: 'Wikipedia — Probe card', u: 'https://en.wikipedia.org/wiki/Probe_card' },
    { t: 'Wikipedia — Wafer testing', u: 'https://en.wikipedia.org/wiki/Wafer_testing' },
    { t: 'ITC / Cerprobe — Introduction to Probe Cards, SWTW 1998', u: 'http://www.swtest.org/swtw_library/1998proc/PDF/T2_itc1.pdf' },
    { t: 'Tektronix / Keithley — Probe Card Tutorial', u: 'https://www.tek.com/en/documents/whitepaper/probe-card-tutorial' },
    { t: 'Goldstein — Probe Cards Enable Wafer-level Test, Solid State Technology 2005', u: 'https://sst.semiconductor-digest.com/2005/12/probe-cards-enable-wafer-level-test/' },
    { t: 'Tunaboylu & Soydan — MEMS Technologies Enabling the Future Wafer Test Systems, IntechOpen 2018', u: 'https://www.intechopen.com/chapters/58798' },
    { t: 'Goel & Marinissen — On-Chip Test Infrastructure Design for Optimal Multi-Site Testing', u: 'https://arxiv.org/pdf/0710.4687' },
    { t: 'FormFactor — CM300xi data sheet', u: 'https://www.formfactor.com/download/cm300xi-data-sheet/?wpdmdl=3294' },
    { t: 'MPI — TS150 / TS200 / TS300 probe systems', u: 'https://www.mpi-corporation.com/ast/engineering-probe-systems/mpi-manual-probe-systems/mpi-ts150-ts200-ts300/' },
    { t: 'US10416228B2 (Tokyo Seimitsu) — Prober', u: 'https://patents.google.com/patent/US10416228B2/en' },
    { t: 'Tokyo Electron — Inspection Features, P-8 Prober Family, SWTW 1997', u: 'http://www.swtest.org/swtw_library/1997proc/PDF/tel8_ml.pdf' },
    { t: 'Vallauri et al. (Technoprobe) — TPEG MEMS vertical probes, SWTW 2012', u: 'https://www.swtest.org/swtw_library/2012proc/PDF/S05_04_Vallauri_SWTW2012.pdf' },
    { t: 'Mialhe et al. (K&S) — Cobra FP Probe Card, SWTW 2005', u: 'https://www.swtest.org/swtw_library/2005proc/PDF/S04_02_Mialhe.pdf' },
    { t: 'Lindsey et al. — How To Buckle Under Pressure, SWTW 2009', u: 'https://www.swtest.org/swtw_library/2009proc/PDF/S01_02_Lindsey_SWTW2009.pdf' },
    { t: 'Broz et al. (MJC) — Advanced Vertical Technologies for Low Damage Probing, SWTW 2017', u: 'https://www.swtest.org/swtw_library/2017proc/PDF/S07_01_Broz_SWTW2017R2.pdf' },
    { t: 'Sangiorgio & Vettori (Technoprobe) — TPEG Mantis, SWTW 2018', u: 'http://www.swtest.org/swtw_library/2018proc/PDF/S03_01_Vettori_SWTW2018.pdf' },
    { t: 'Yun & Vallauri (Technoprobe) — HBM microbump probing, SWTW 2017', u: 'https://www.swtest.org/swtw_library/2017proc/PDF/S03_01_Vallauri_SWTW2017.pdf' },
    { t: 'Bischoff et al. (TI / ITS / FormFactor) — SWTW 2012', u: 'https://www.swtest.org/swtw_library/2012proc/PDF/S02_02_Bischoff_SWTW2012.pdf' },
    { t: 'Doutre et al. — SWTW 2015', u: 'https://www.swtest.org/swtw_library/2015proc/PDF/S05_03_Doutre_SWTW2015R.pdf' },
    { t: 'US5773987A — cantilever probe scrub', u: 'https://patents.google.com/patent/US5773987A/en' },
    { t: 'US10996243B2 — vertical probe force curve', u: 'https://patents.google.com/patent/US10996243B2/en' },
    { t: 'Electronic Design — Wafer Testing with Tungsten and Tungsten-Rhenium Probe Needles', u: 'https://www.electronicdesign.com/home/article/21199980/wafer-testing-with-tungsten-and-tungsten-rhenium-probe-needles' },
    { t: 'Wolfe (TI / MJC) — 50 μm pitch vertical probing, SWTW 2009', u: 'https://www.swtest.org/swtw_library/2009proc/PDF/S08_02_Wolfe_SWTW2009.pdf' },
    { t: 'SemiEngineering — Delivering On Power During HPC Test, 2024', u: 'https://semiengineering.com/delivering-on-power-during-hpc-test/' },
    { t: 'Ghidoni et al. (Technoprobe / Advantest) — Towards Ultra-High Pin Count Probe Card, SWTest Asia 2024', u: 'https://www.swtestasia.org/2024proc/pdf/poster/P00_15_GHIDONI_SWTestAsia2024.pdf' },
    { t: 'Hsieh (MPI) — 100K+ Ultra High Pin Count Probe Card, SWTest Asia 2024', u: 'https://www.swtestasia.org/2024proc/pdf/T02_03_HSIEH_SWTestAsia2024.pdf' },
    { t: 'FormFactor — AI Processors (high-volume wafer test)', u: 'https://www.formfactor.com/applications/high-volume-test-on-wafer/ai-processors/' },
    { t: 'Dastmalchi, Heitzer & Harker — Advancing Probe Card Parallelism for SOC Devices, SWTest 2022', u: 'https://www.swtest.org/library/2022proc/pdf/M03_03_Dastmalchi_SWTest_2022F.pdf' },
    { t: 'SemiEngineering — Cleaning Up During IC Test', u: 'https://semiengineering.com/cleaning-up-during-ic-test/' },
    { t: 'Broz et al. — Probe Card Cleaning: A Short Tutorial, SWTW 2007', u: 'https://www.swtest.org/swtw_library/2007proc/PDF/T00_01_Broz_SWTW2007.pdf' },
    { t: 'US7217139B2 — Interconnect assembly for a probe card', u: 'https://patents.google.com/patent/US7217139B2/en' },
    { t: 'US11209463B2 (Technoprobe) — Probe card for a testing apparatus', u: 'https://patents.google.com/patent/US11209463B2/en' },
    { t: 'FICT — probe card PCB examples', u: 'https://www.fict-g.com/en/product/probe.html' },
    { t: 'DIS Tech — Our technologies', u: 'https://www.dis.tech/technologies-and-products/our-technologies' },
    { t: 'DIS Tech — company site', u: 'https://www.dis.tech/' },
    { t: 'Teradyne — Form 10-K, fiscal year 2024', u: 'https://www.sec.gov/Archives/edgar/data/97210/000095017025023784/ter-20241231.htm' },
    { t: 'KYEC — Wafer Probing service', u: 'https://www.kyec.com.tw/en/Service/wafer-probing' },
  ],
};
