// Where the simulator's numbers come from. index.html renders this in the 參數依據 panel,
// and make_refs.py copies it into README.md. Reference numbers are 1-based positions in `refs`.
window.SOURCES = {
  intro: '這是示意模型：幾何尺寸有放大，物理是簡化公式。下面列出每個步驟和可調參數用的數值、公開資料裡的典型範圍，以及出處。所有來源都是公開文件；數字是業界通用量級，不是任何產品或專案的規格。',
  steps: [
    { zh: '上片與對位（模擬器省略）', d: '晶圓從晶舟載入、做晶圓對位，再用上看／下看相機把探針對準鋁墊（PTPA）。', r: [3, 10] },
    { zh: '步進 INDEX', d: '載台在 XY 方向移到下一組晶粒。含 Z 軸上下，典型步進時間約 0.7 秒。', r: [2, 7] },
    { zh: '上升接觸 Z-UP', d: '載台抬升，直到探針第一次碰到鋁墊（first contact）。', r: [3, 10] },
    { zh: '過驅 OVERDRIVE', d: '接觸後再往上壓一段距離，補償探針高低差，並讓針尖刮破鋁墊表面的氧化層。', r: [3, 5, 20] },
    { zh: '電性測試 TEST', d: '訊號由測試機經彈簧針、主板、MLO 載板、探針到晶粒。測試時間通常遠大於移動時間。', r: [31, 34, 7] },
    { zh: '離開 RELEASE', d: '載台下降，晶粒依結果分 bin 記進晶圓圖，再換下一組。', r: [30, 2] },
    { zh: '清針與針痕檢查', d: '每隔數十到上百次下針，用清針片清掉針尖的沾黏物，並定期檢查針痕（PMI）。模擬器只做了計數和接觸電阻漂移。', r: [29, 30, 11] },
    { zh: '溫度（模擬器省略）', d: '量產常在 −55 °C 到 150–200 °C 之間測試，探針卡和機台都需要預熱。', r: [37] },
  ],
  params: [
    { p: '過驅量 Overdrive', sim: '0–200 μm，預設 75 μm；標示的常用範圍 50–100 μm', real: '懸臂針 25–100 μm，常用 50–75 μm；垂直針在鋁墊上約 75 μm；凸塊／銅柱可到 150–200 μm', r: [3, 4, 5, 17, 15] },
    { p: '懸臂針針壓', sim: '0.06 gf/μm，75 μm 時約 4.5 gf（線性）', real: '鎢／鎢錸針 1.0–2.5 gf/mil，也就是 0.04–0.10 gf/μm', r: [4, 19] },
    { p: '垂直針針壓', sim: 'Cobra 型挫曲針：75 μm 時約 4.5 gf，之後趨平', real: 'Cobra／挫曲針在 75 μm 約 4.5–6.5 g；新一代 MEMS 垂直針只有 1–3 g', r: [12, 13, 14, 21, 24] },
    { p: '針痕長度', sim: '懸臂 ≈ 0.22×OD＋6 μm（75 μm 時約 23 μm）；垂直 ≈ 0.05×OD＋10 μm（約 14 μm）', real: '懸臂 15–25 μm（文獻範圍 13–38 μm）；垂直 11–18 μm，主要是針尖本身的大小', r: [20, 18, 16, 15, 13] },
    { p: '鋁墊尺寸', sim: '60 μm', real: '打線鋁墊約 55–90 μm 見方', r: [4, 13, 16] },
    { p: '接觸電阻 CRES', sim: '壓穩後約 0.1–0.3 Ω；過驅量太小時偏高', real: '穩定值 < 0.25–0.3 Ω，規格常訂 < 1 Ω；過驅量超過約 25–60 μm 才會穩定', r: [13, 17, 18, 6] },
    { p: '過載上限（示意）', sim: '懸臂 125 μm、垂直 170 μm', real: '懸臂針過驅量一般不超過 127 μm，否則針尖會損傷；挫曲針常用到 150 μm；MEMS 垂直針多限制在 100 μm。公開資料沒有實測的塑性變形門檻', r: [22, 16, 14, 15] },
    { p: '平整度', sim: '翹曲 0–100 μm，超過 25 μm 標為超標', real: '探針平整度規格約 ≤25 μm 或 ±10–20 μm；受力或升溫後整張卡可再變形數十 μm', r: [4, 23, 17, 26] },
    { p: '探針尺寸與材質', sim: '垂直針長約 5 mm；懸臂針為鎢錸', real: 'Cobra／挫曲針長 4.3–6.4 mm、線徑 25–64 μm；鎢錸是最常見的懸臂針材料', r: [13, 4, 22] },
    { p: 'Z 分離距離', sim: '200 μm', real: '公開規格為 200–300 μm，量產機台由 recipe 設定', r: [8, 9] },
    { p: '每次移動時間', sim: '0.7 秒（步進 0.35＋上升 0.15＋過驅 0.08＋離開 0.12）', real: '典型步進時間 0.7 秒；工程機台 0.75–1.5 秒', r: [7, 8] },
    { p: '每次測試時間', sim: '0.2–60 秒，預設 1.5 秒（約 27 次／分）；另有 10×、60× 快轉', real: '依產品從數秒到數分鐘，公開例子有 5 秒、10 秒、180 秒', r: [1, 28, 7] },
    { p: '同測顆數', sim: '每次下針 4 顆', real: '大晶粒的 AI 處理器 x8–x16；一般邏輯可達 128 顆以上；DRAM 可以一次測完整片', r: [27, 28, 1] },
    { p: '清針間隔', sim: '每 100 次下針；接觸電阻隨次數緩慢升高（示意）', real: '常見做法是每 50–100 次清一次，實際間隔依產品調整', r: [29, 30] },
    { p: '探針數與總針壓', sim: '這張卡 224 針', real: 'HPC 卡約 2 萬針、每針約 2 g；最新的卡超過 10 萬針，總針壓 170–280 kgf，接近載台約 300 kgf 的上限', r: [24, 25, 26] },
    { p: '晶圓與晶粒', sim: '300 mm 晶圓、約 18 mm 晶粒、157 顆', real: '18 mm 晶粒、邊緣排除 3 mm 時約 170–180 顆毛晶粒（依標準公式推算）', r: [] },
    { p: '主板層數', sim: '標示「數十層」', real: '公開的探針卡 PCB 例子為 42–76 層、厚 2.7–9.6 mm', r: [33] },
    { p: '探針卡結構與 DIS', sim: '彈簧針塔 → 補強板 → 主板 → MLO 載板 → 探針頭 → 晶圓', real: '主板、（中介層）、空間轉換板、探針頭的組成與專利描述一致；補強板是機構件，不在訊號路徑上。DIS Tech 在 2024 年 5 月由 Technoprobe 自 Teradyne 收購', r: [31, 32, 34, 35, 36] },
  ],
  // the game (game/) adds these mechanics on top of the simulator's model
  game: [
    { p: '誤判', sim: '最後碰到的探針接觸電阻超過 0.5 Ω 開始有好晶粒被判成不良，1.3 Ω 以上約九成（示意）', real: '接觸電阻規格常訂 < 1 Ω；接觸電阻升高是針測誤判的主要來源', r: [13, 18, 29] },
    { p: '平整度', sim: '最後碰到的探針，實際過驅量 = 過驅量 − 平整度。一般關卡 10–15 μm；第 4 關載板再翹 50 μm，整平後 15 μm', real: '探針平整度規格約 ≤25 μm 或 ±10–20 μm', r: [4, 23, 17] },
    { p: '小鋁墊（第 2 關）', sim: '鋁墊 40 μm，對位誤差 ±4 μm', real: '50 μm 間距的產品，鋁墊只有 40 μm 上下；針痕要留在鋁墊內，懸臂針的可用範圍很窄', r: [23, 15, 20] },
    { p: '鋁墊壓傷', sim: 'Cobra 針實際過驅量 120 μm 以上、MEMS 針 88 μm 以上開始有機率壓傷；125 °C 時從 80 μm 起（示意）', real: '針痕面積隨過驅量變大；車用產品對針痕面積訂有上限，高溫下還有銲球脫落的風險。公開資料沒有通用的門檻值', r: [15, 40] },
    { p: '清針的代價', sim: '每次清針 12–15 秒，並扣 0.6 分代表針尖磨耗；每次下針讓接觸電阻升高 7–9 mΩ（比實際快，方便在幾片晶圓內看到效果）', real: '常見每 50–100 次清一次；公開例子：每 100 顆晶粒清一次，每次下針 25 下、過驅量 20 μm', r: [29, 30, 40] },
    { p: '整張卡受力變形（第 5 關）', sim: '10 萬針；總針壓每增加 1 kgf，卡與機台退讓 1 μm；載台上限 300 kgf', real: '4 萬針的卡，實際過驅量最好也只有設定值的一半左右；10 萬針的卡總針壓 170–280 kgf，接近載台約 300 kgf 的上限', r: [38, 25, 26, 24] },
    { p: '高溫漂移（第 6 關）', sim: '125 °C；冷卡的針尖比熱卡遠 60 μm。升溫時間常數 60 秒，載台移開後以 120 秒冷卻（時間大幅壓縮）', real: '室溫到 90 °C，大面積探針卡的針尖高度可變化 50 μm；175 °C 下最好的卡約 15 μm。實際預熱：機台 2 小時、探針卡 10–15 分鐘。清針、換片把載台移開幾分鐘，針尖高度會再跑掉', r: [39, 40, 41] },
    { p: '微凸塊（第 7 關）', sim: '30 μm 的銅柱凸塊；針痕直徑 = 8 μm × 針壓（g）。針痕超過凸塊直徑的 52% 開始算受損，66% 以上一定受損。凸塊高低差 6 μm；每次下針讓接觸電阻升高 8 mΩ（示意）', real: '30 μm 的銅柱上，針壓每差 0.5 g，針痕差 4 μm。規格常訂針痕直徑小於凸塊直徑的 50%（常見 50–70%），或針痕面積小於 25%。凸塊高度的容許差約 10%。微凸塊要求針壓低於 1.5 gf；在凸塊上每 50–250 次下針清一次', r: [42, 15, 45, 51, 43, 44] },
    { p: '大電流（第 8 關）', sim: '每顆晶粒 120 A，由 300 支電源探針分擔，平均每支 0.4 A；反覆使用的上限 0.65 A。針尖越髒，最吃重的那支針扛得越多（最多約 2.5 倍）。3.5% 的晶粒短路；沒有先篩就送全電壓，一次燒掉 2–4 支針，燒掉 24 支就得停機（示意）', real: '載流能力（CCC）定義為讓針壓永久下降 20% 的電流；反覆使用的上限（MAC）約為 CCC 的 0.6–0.8 倍，公開例子為 0.28–0.74 A。設計目標是每針 0.5 A。公開例子：12 支電源針裡有 2 支扛了 80% 的電流；短路晶粒的瞬間電流可超過 10 A。做法是先用低電壓和低的電流上限篩短路，再對好的晶粒送全功率', r: [46, 47, 48, 49, 52, 24] },
    { p: '重工整平（第 4 關）', sim: '載板翹曲 50 → 15 μm，花 60 秒（示意）', real: '遊戲設計。實際上是把卡送回供應商重新整平，需要數天', r: [] },
    { p: '計分', sim: '正確測出且沒受傷的好晶粒比例，再扣清針、超時和損壞的分數', real: '遊戲設計，不是業界指標', r: [] },
  ],
  left: '模擬器沒有做的部分：溫度、上片與對位、針痕檢查、探針磨耗與壽命（公開資料為 100 萬次以上）、電流承載能力，以及整張卡受力後的變形（高針數卡上，實際過驅量只有設定值的一部分）。溫度、整張卡的變形和電流承載能力，在遊戲的第 5、6、8 關有簡化的版本。',
  refs: [
    { t: 'Wikipedia — Probe card', u: 'https://en.wikipedia.org/wiki/Probe_card' },
    { t: 'Wikipedia — Wafer testing', u: 'https://en.wikipedia.org/wiki/Wafer_testing' },
    { t: 'ITC / Cerprobe — Introduction to Probe Cards, SWTW 1998', u: 'http://www.swtest.org/swtw_library/1998proc/PDF/T2_itc1.pdf' },
    { t: 'Tektronix / Keithley — Probe Card Tutorial', u: 'https://www.tek.com/en/documents/whitepaper/probe-card-tutorial' },
    { t: 'Goldstein — Probe Cards Enable Wafer-level Test, Solid State Technology 2005', u: 'https://sst.semiconductor-digest.com/2005/12/probe-cards-enable-wafer-level-test/' },
    { t: 'Tunaboylu & Soydan — MEMS Technologies Enabling the Future Wafer Test Systems, IntechOpen 2018', u: 'https://www.intechopen.com/chapters/58798' },
    { t: 'Goel & Marinissen — On-Chip Test Infrastructure Design for Optimal Multi-Site Testing', u: 'https://arxiv.org/pdf/0710.4687' },
    { t: 'FormFactor — CM300xi data sheet', u: 'https://www.formfactor.com/download/cm300xi-data-sheet/?wpdmdl=3294' },
    { t: 'MPI — TS150 / TS200 / TS300 probe systems', u: 'https://www.mpi-corporation.com/ast/engineering-probe-systems/mpi-manual-probe-systems/mpi-ts150-ts200-ts300/' },
    { t: 'US10416228B2 (Tokyo Seimitsu) — Prober', u: 'https://patents.google.com/patent/US10416228B2/en' },
    { t: 'Tokyo Electron — Inspection Features, P-8 Prober Family, SWTW 1997', u: 'http://www.swtest.org/swtw_library/1997proc/PDF/tel8_ml.pdf' },
    { t: 'Vallauri et al. (Technoprobe) — TPEG MEMS vertical probes, SWTW 2012', u: 'https://www.swtest.org/swtw_library/2012proc/PDF/S05_04_Vallauri_SWTW2012.pdf' },
    { t: 'Mialhe et al. (K&S) — Cobra FP Probe Card, SWTW 2005', u: 'https://www.swtest.org/swtw_library/2005proc/PDF/S04_02_Mialhe.pdf' },
    { t: 'Lindsey et al. — How To Buckle Under Pressure, SWTW 2009', u: 'https://www.swtest.org/swtw_library/2009proc/PDF/S01_02_Lindsey_SWTW2009.pdf' },
    { t: 'Broz et al. (MJC) — Advanced Vertical Technologies for Low Damage Probing, SWTW 2017', u: 'https://www.swtest.org/swtw_library/2017proc/PDF/S07_01_Broz_SWTW2017R2.pdf' },
    { t: 'Sangiorgio & Vettori (Technoprobe) — TPEG Mantis, SWTW 2018', u: 'http://www.swtest.org/swtw_library/2018proc/PDF/S03_01_Vettori_SWTW2018.pdf' },
    { t: 'Yun & Vallauri (Technoprobe) — HBM microbump probing, SWTW 2017', u: 'https://www.swtest.org/swtw_library/2017proc/PDF/S03_01_Vallauri_SWTW2017.pdf' },
    { t: 'Bischoff et al. (TI / ITS / FormFactor) — SWTW 2012', u: 'https://www.swtest.org/swtw_library/2012proc/PDF/S02_02_Bischoff_SWTW2012.pdf' },
    { t: 'Doutre et al. — SWTW 2015', u: 'https://www.swtest.org/swtw_library/2015proc/PDF/S05_03_Doutre_SWTW2015R.pdf' },
    { t: 'US5773987A — cantilever probe scrub', u: 'https://patents.google.com/patent/US5773987A/en' },
    { t: 'US10996243B2 — vertical probe force curve', u: 'https://patents.google.com/patent/US10996243B2/en' },
    { t: 'Electronic Design — Wafer Testing with Tungsten and Tungsten-Rhenium Probe Needles', u: 'https://www.electronicdesign.com/home/article/21199980/wafer-testing-with-tungsten-and-tungsten-rhenium-probe-needles' },
    { t: 'Wolfe (TI / MJC) — 50 μm pitch vertical probing, SWTW 2009', u: 'https://www.swtest.org/swtw_library/2009proc/PDF/S08_02_Wolfe_SWTW2009.pdf' },
    { t: 'SemiEngineering — Delivering On Power During HPC Test, 2024', u: 'https://semiengineering.com/delivering-on-power-during-hpc-test/' },
    { t: 'Ghidoni et al. (Technoprobe / Advantest) — Towards Ultra-High Pin Count Probe Card, SWTest Asia 2024', u: 'https://www.swtestasia.org/2024proc/pdf/poster/P00_15_GHIDONI_SWTestAsia2024.pdf' },
    { t: 'Hsieh (MPI) — 100K+ Ultra High Pin Count Probe Card, SWTest Asia 2024', u: 'https://www.swtestasia.org/2024proc/pdf/T02_03_HSIEH_SWTestAsia2024.pdf' },
    { t: 'FormFactor — AI Processors (high-volume wafer test)', u: 'https://www.formfactor.com/applications/high-volume-test-on-wafer/ai-processors/' },
    { t: 'Dastmalchi, Heitzer & Harker — Advancing Probe Card Parallelism for SOC Devices, SWTest 2022', u: 'https://www.swtest.org/library/2022proc/pdf/M03_03_Dastmalchi_SWTest_2022F.pdf' },
    { t: 'SemiEngineering — Cleaning Up During IC Test', u: 'https://semiengineering.com/cleaning-up-during-ic-test/' },
    { t: 'Broz et al. — Probe Card Cleaning: A Short Tutorial, SWTW 2007', u: 'https://www.swtest.org/swtw_library/2007proc/PDF/T00_01_Broz_SWTW2007.pdf' },
    { t: 'US7217139B2 — Interconnect assembly for a probe card', u: 'https://patents.google.com/patent/US7217139B2/en' },
    { t: 'US11209463B2 (Technoprobe) — Probe card for a testing apparatus', u: 'https://patents.google.com/patent/US11209463B2/en' },
    { t: 'FICT — probe card PCB examples', u: 'https://www.fict-g.com/en/product/probe.html' },
    { t: 'DIS Tech — Our technologies', u: 'https://www.dis.tech/technologies-and-products/our-technologies' },
    { t: 'DIS Tech — company site', u: 'https://www.dis.tech/' },
    { t: 'Teradyne — Form 10-K, fiscal year 2024', u: 'https://www.sec.gov/Archives/edgar/data/97210/000095017025023784/ter-20241231.htm' },
    { t: 'KYEC — Wafer Probing service', u: 'https://www.kyec.com.tw/en/Service/wafer-probing' },
    { t: 'Huebner (FormFactor) — 40k Probes on 300mm: Another Step Towards 1 Touchdown DRAM Sort, SWTW 2008', u: 'https://www.formfactor.com/wp-content/uploads/S05_02_Huebner_SWTW2008.pdf' },
    { t: 'US8531202B2 — Probe card test apparatus and method', u: 'https://patents.google.com/patent/US8531202B2/en' },
    { t: 'Van Cauwenberghe (ON Semiconductor) — Wafer Probe Challenges for the Automotive Market, SWTW 2012', u: 'https://www.swtest.org/swtw_library/2012proc/PDF/S01_03_Cauwenberghe_SWTW2012.pdf' },
    { t: 'Sinsheimer & Buckholtz (Teradyne) — Wafer Sort at Extreme Temperatures, SWTW 2018', u: 'https://www.swtest.org/swtw_library/2018proc/PDF/P01_02_Buckholtz_SWTW2018.pdf' },
    { t: 'Wittig, Leong et al. (GLOBALFOUNDRIES / FormFactor) — Key Considerations to Probe Cu Pillars in High Volume Production, 2014', u: 'https://www.formfactor.com/wp-content/uploads/S05_01_Leong_06-01-2014_Final.pdf' },
    { t: 'Liao (FormFactor) — Probe Card Solution to Address Leading-Edge Advanced Package Test Requirements, 2021', u: 'https://compass.formfactor.com/wp-content/uploads/2021-Probe-Card-Solution-to-Address-Leading-Edge-Advanced-Package-Test-Requirements-Alan-Liao.pdf' },
    { t: 'Mai & Mai (JEM) — Probing Challenges with Cu Pillar, SWTW 2017', u: 'https://www.swtest.org/swtw_library/2017proc/PDF/S07_03_Mai_SWTW2017R2.pdf' },
    { t: 'Angles & Vallauri (STMicroelectronics / Technoprobe) — Addressing 80 µm pitch Cu Pillar Bump Wafer Probing, SWTW 2014', u: 'https://www.swtest.org/swtw_library/2014proc/PDF/SWTW2014_19.pdf' },
    { t: 'Daniels (Texas Instruments) — ISMI Probe Council Current Carrying Capability Measurement Standard, SWTW 2009', u: 'https://www.swtest.org/swtw_library/2009proc/PDF/S08_03_Daniels_SWTW2009.pdf' },
    { t: "Cassier, Folwarski, Kister & Leong (Qualcomm / FormFactor) — Determining Probe's Maximum Allowable Current, SWTW 2015", u: 'https://www.swtest.org/swtw_library/2015proc/PDF/S01_01_Kister_SWTW2015R.pdf' },
    { t: 'Huebner (FormFactor) — A Hot Topic: Current Carrying Capacity, Tip Melting and Arcing, SWTW 2011', u: 'https://www.swtest.org/swtw_library/2011proc/PDF/S03_01_Huebner_SWTW2011.pdf' },
    { t: 'Gaggl, Newman & Kaczinsky — Aspects of High Power Probing, SWTW 2011', u: 'https://www.swtest.org/swtw_library/2011proc/PDF/S03_03_Gaggl_SWTW2011.pdf' },
    { t: 'Dabrowiecki (Feinmetall) — A finite element analysis of copper pillar bump probing, 2016', u: 'https://www.electronicdesign.com/home/article/21206303/a-finite-element-analysis-of-copper-pillar-bump-probing' },
    { t: 'SemiEngineering — Challenges Grow For Creating Smaller Bumps For Flip Chips, 2023', u: 'https://semiengineering.com/challenges-grow-for-creating-smaller-bumps-for-flip-chips/' },
    { t: 'Claudius (Intel) — SIU Probe Burn Control, SWTW 2005', u: 'https://www.swtest.org/swtw_library/2005proc/PDF/T01_04_Claudius.pdf' },
  ],
};
