"""Narration for the Final Test Board Lab tour.

  python ft/narration.py tts    # synthesize the lines, fit the tour to them, write ft/narration.js
  python ft/narration.py mix    # lay the narration over ft/build/silent.mp4 -> ft/ft-board-lab.mp4

Same voice, same Gemini TTS + whisper check as ../narration.py; only the script and the file locations differ.
A line with `at` is pinned to that moment of the tour (original timeline); `ins` says where the tour may
pause if the previous lines run long. Lines without `at` follow the one before.
"""
import json, os, shutil, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
sys.stdout.reconfigure(encoding="utf-8")
import narration as N

AUDIO = os.path.join(HERE, "audio")
LINES = [
    dict(at=0.3, zh="封裝好的晶片，出貨前還要再測一次，這一站叫成品測試。", en="A packaged chip is tested once more before it ships. This step is final test."),
    dict(zh="分類機一次抓起四顆，壓進測試座。", en="The handler picks four at a time and presses them into the sockets."),
    dict(at=7.1, ins=6.2, zh="把整個測試介面拆開。", en="Take the whole interface apart."),
    dict(zh="由下往上：測試頭、彈簧針介面、測試載板、測試座、晶片。", en="Bottom to top: test head, spring-pin interface, load board, sockets, devices."),
    dict(zh="中間這塊測試載板，是 DIS 做的。", en="The load board in the middle is what DIS builds."),
    dict(at=15.1, ins=14.2, zh="追一條訊號：從測試頭往上，穿過載板的內層，", en="Follow one signal: up from the test head, through the inner layers of the board,"),
    dict(zh="再經過測試座裡的彈簧針，到達錫球。", en="then through a spring probe in the socket, to a solder ball."),
    dict(at=27.9, ins=27.2, zh="剖開測試座：每顆錫球底下，都有一支彈簧針。", en="Cut a socket open: there is one spring probe under every ball."),
    dict(at=31.4, ins=30.6, zh="時間放慢十倍。", en="Slow time down ten times."),
    dict(zh="壓頭往下壓，彈簧針縮進去零點四毫米，每支推回來將近三十克。", en="The pusher comes down; every pin compresses 0.4 mm and pushes back with nearly 30 grams."),
    dict(at=38.0, ins=37.2, zh="凍結時間，讓封裝翹曲。", en="Freeze time and warp the package."),
    dict(at=41.4, ins=41.35, zh="角落的錫球碰不到探針，變紅了。", en="The corner balls no longer reach their pins — they turn red."),
    dict(at=42.8, ins=42.0, zh="那就加大下壓行程⋯⋯直到探針壓到底。", en="So add more stroke… until the pins bottom out."),
    dict(at=49.5, ins=48.6, zh="最後看產出：同測顆數從四顆變八顆，", en="Finally, throughput: go from four sites to eight,"),
    dict(zh="每小時產出卻沒有加倍，因為換料時間還在，測試時間也變長了。", en="and the output does not double: the index time is still there, and the test takes longer."),
    dict(at=56.0, ins=55.8, cap=False, zh="從晶圓到成品，每一顆晶片都要被碰兩次。", en="From wafer to package, every chip gets touched twice."),
    dict(cap=False, zh="用 Claude Opus 5.5 做的，直接在瀏覽器裡就能玩。", en="Built with Claude Opus 5.5 — it runs live in your browser."),
]
TOUR_END = 61.5


def tts():
    os.makedirs(AUDIO, exist_ok=True)
    for l in LINES:
        l["file"] = os.path.join(AUDIO, f"{N.key(l['zh'])}.mp3")
    for l in LINES:                                     # a line shared with the Probe Card Lab tour is reused, not re-recorded
        shared = os.path.join(N.AUDIO, os.path.basename(l["file"]))
        if not os.path.exists(l["file"]) and os.path.exists(shared):
            shutil.copyfile(shared, l["file"])
    todo = [l for l in LINES if not os.path.exists(l["file"])]
    print(f"{len(LINES)} lines, {len(todo)} to synthesize", flush=True)
    if todo:
        N.synth_gemini(todo)
    want = {os.path.basename(l["file"]) for l in LINES}
    for f in os.listdir(AUDIO):
        if f.endswith(".mp3") and f not in want:
            os.remove(os.path.join(AUDIO, f))
    retime = []
    T = lambda t: t + sum(e for a, e in retime if t >= a)
    cursor, out = 0.0, []
    for l in LINES:
        d = N.duration(l["file"])
        if "at" in l:
            assert l.get("ins", l["at"]) <= l["at"], l["zh"]
            start = T(l["at"]) + N.LEAD
            late = cursor + N.GAP - start
            if late > 0.02:
                retime.append((l.get("ins", l["at"]), round(late, 3)))
                start = T(l["at"]) + N.LEAD
        else:
            start = cursor + N.GAP
        out.append(dict(t=round(start, 3), d=round(d, 3), zh=l["zh"], en=l["en"], cap=l.get("cap", True), src="audio/" + os.path.basename(l["file"])))
        cursor = start + d
    end = round(max(T(TOUR_END), cursor + N.TAIL), 3)
    data = dict(retime=retime, lines=out, end=end)
    with open(os.path.join(HERE, "narration.json"), "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
    with open(os.path.join(HERE, "narration.js"), "w", encoding="utf-8", newline="\n") as f:
        f.write("// generated by narration.py — voice lines + how far the tour stretches to fit them\n")
        f.write("window.FT_NARR = " + json.dumps(data, ensure_ascii=False) + ";\n")
    for a, e in retime:
        print(f"  stretch +{e:.2f}s at t={a}")
    print(f"{len(out)} lines, tour length {end:.1f}s")


def mix():
    data = json.load(open(os.path.join(HERE, "narration.json"), encoding="utf-8"))
    silent, final = os.path.join(HERE, "build", "silent.mp4"), os.path.join(HERE, "ft-board-lab.mp4")
    cmd, parts = ["ffmpeg", "-y", "-v", "error", "-i", silent], []
    for i, l in enumerate(data["lines"]):
        cmd += ["-i", os.path.join(HERE, l["src"])]
        ms = int(l["t"] * 1000)
        parts.append(f"[{i + 1}:a]aresample=48000,adelay={ms}|{ms}[a{i}]")
    n = len(data["lines"])
    graph = ";".join(parts) + ";" + "".join(f"[a{i}]" for i in range(n)) + f"amix=inputs={n}:normalize=0,loudnorm=I=-16:TP=-1.5:LRA=11,apad[aout]"
    cmd += ["-filter_complex", graph, "-map", "0:v", "-map", "[aout]", "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-ar", "48000", "-shortest", "-movflags", "+faststart", final]
    subprocess.check_call(cmd)
    print("wrote", final)


if __name__ == "__main__":
    {"tts": tts, "mix": mix}[sys.argv[1] if len(sys.argv) > 1 else "tts"]()
