"""Narration for the Signal & Power Integrity Lab tour.

  python si/narration.py tts            # synthesize the lines, fit the tour to them, write si/narration.js
  python si/narration.py mix [name]     # lay the narration over si/build/silent[-name].mp4 -> si/si-pi-lab[-name].mp4

Same voice and the same Gemini TTS + whisper check as ../narration.py; only the script and the file locations differ.
A line with `at` is pinned to that moment of the tour (original timeline); `ins` says where the tour may
pause if the previous lines run long. Lines without `at` follow the one before.
"""
import json, os, shutil, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
sys.stdout.reconfigure(encoding="utf-8")
import narration as N

AUDIO = os.path.join(HERE, "audio")
LINES = [
    dict(at=0.3, zh="測試板很厚，訊號要從底面一路穿到頂面的晶片。", en="A test board is thick, and the signal has to travel from the bottom side up to the chip on top."),
    dict(zh="導通孔用不到的那一截叫殘樁，它會在某個頻率把訊號吃掉，眼圖整個閉上了。", en="The unused part of a via is a stub. At one frequency it swallows the signal, and the eye closes."),
    dict(at=6.8, ins=5.8, zh="把兩邊的殘樁背鑽掉，損耗曲線上的缺口就不見了。", en="Back-drill both stubs and the notches in the loss curve are gone."),
    dict(at=15.0, ins=14.0, zh="再換成低損耗的板材，眼睛就張開了。", en="Switch to a low-loss laminate and the eye opens."),
    dict(at=20.0, ins=19.0, zh="速率拉到 112 G，改用四階調變，三個眼都很小。", en="Go to 112 gigabits with four-level signalling: three eyes, all small."),
    dict(at=24.3, ins=23.4, zh="打開接收端的等化，眼睛又張開一些。", en="Turn on the receiver equaliser and the eyes open a little."),
    dict(at=28.7, ins=27.6, zh="另一個難題是電源。電流一跳，電壓就往下掉。", en="The other problem is power. When the current steps, the voltage sags."),
    dict(zh="目標阻抗等於電壓乘上容許的漣波，再除以電流的跳升量，這裡是兩百四十微歐姆。", en="Target impedance is voltage times allowed ripple, divided by the current step: 240 micro-ohms here."),
    dict(at=36.1, ins=35.2, zh="加大電容，撐住慢的那一段；", en="Bulk capacitors hold up the slow part;"),
    dict(at=39.8, ins=39.0, zh="增加電源接腳、降低電感，撐住快的那一段；", en="more power pins cut the inductance and hold up the fast part;"),
    dict(at=43.3, ins=42.6, zh="中間再用中電容和高頻電容接力。", en="mid and high-frequency capacitors cover the middle."),
    dict(at=49.2, ins=48.4, zh="電流加到一千安培，目標阻抗只剩四十幾微歐姆，又不夠了。", en="At a thousand amps the target drops below fifty micro-ohms, and it is not enough again."),
    dict(at=54.6, ins=54.2, cap=False, zh="訊號要走得乾淨，電要送得穩，這就是測試板在做的事。", en="A clean path for the signal and a stiff rail for the power: that is the job of a test board."),
    dict(cap=False, zh="用 Claude Opus 5.5 做的，直接在瀏覽器裡就能玩。", en="Built with Claude Opus 5.5 — it runs live in your browser."),
]
TOUR_END = 60.0


def tts():
    os.makedirs(AUDIO, exist_ok=True)
    for l in LINES:
        l["file"] = os.path.join(AUDIO, f"{N.key(l['zh'])}.mp3")
    for l in LINES:                                     # a line shared with the Probe Card Lab tour is reused, not re-recorded
        shared = os.path.join(N.AUDIO, os.path.basename(l["file"]))
        if not os.path.exists(l["file"]) and os.path.exists(shared):
            shutil.copyfile(shared, l["file"])
    todo = [l for l in LINES if not os.path.exists(l["file"])]
    print(f"{len(LINES)} lines, {len(todo)} to synthesize", flush=True)
    if todo:
        N.synth_gemini(todo)
    want = {os.path.basename(l["file"]) for l in LINES}
    for f in os.listdir(AUDIO):
        if f.endswith(".mp3") and f not in want:
            os.remove(os.path.join(AUDIO, f))
    retime = []
    T = lambda t: t + sum(e for a, e in retime if t >= a)
    cursor, out = 0.0, []
    for l in LINES:
        d = N.duration(l["file"])
        if "at" in l:
            assert l.get("ins", l["at"]) <= l["at"], l["zh"]
            start = T(l["at"]) + N.LEAD
            late = cursor + N.GAP - start
            if late > 0.02:
                retime.append((l.get("ins", l["at"]), round(late, 3)))
                start = T(l["at"]) + N.LEAD
        else:
            start = cursor + N.GAP
        out.append(dict(t=round(start, 3), d=round(d, 3), zh=l["zh"], en=l["en"], cap=l.get("cap", True), src="audio/" + os.path.basename(l["file"])))
        cursor = start + d
    end = round(max(T(TOUR_END), cursor + N.TAIL), 3)
    data = dict(retime=retime, lines=out, end=end)
    with open(os.path.join(HERE, "narration.json"), "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
    with open(os.path.join(HERE, "narration.js"), "w", encoding="utf-8", newline="\n") as f:
        f.write("// generated by narration.py — voice lines + how far the tour stretches to fit them\n")
        f.write("window.SI_NARR = " + json.dumps(data, ensure_ascii=False) + ";\n")
    for a, e in retime:
        print(f"  stretch +{e:.2f}s at t={a}")
    print(f"{len(out)} lines, tour length {end:.1f}s")


def mix(name=""):
    sfx = "-" + name if name else ""
    data = json.load(open(os.path.join(HERE, "narration.json"), encoding="utf-8"))
    silent, final = os.path.join(HERE, "build", f"silent{sfx}.mp4"), os.path.join(HERE, f"si-pi-lab{sfx}.mp4")
    cmd, parts = ["ffmpeg", "-nostdin", "-y", "-v", "error", "-i", silent], []
    for i, l in enumerate(data["lines"]):
        cmd += ["-i", os.path.join(HERE, l["src"])]
        ms = int(l["t"] * 1000)
        parts.append(f"[{i + 1}:a]aresample=48000,adelay={ms}|{ms}[a{i}]")
    n = len(data["lines"])
    graph = ";".join(parts) + ";" + "".join(f"[a{i}]" for i in range(n)) + f"amix=inputs={n}:normalize=0,loudnorm=I=-16:TP=-1.5:LRA=11,apad[aout]"
    cmd += ["-filter_complex", graph, "-map", "0:v", "-map", "[aout]", "-c:v", "copy", "-c:a", "aac", "-b:a", "192k", "-ar", "48000", "-shortest", "-movflags", "+faststart", final]
    subprocess.check_call(cmd)
    print("wrote", final)


if __name__ == "__main__":
    {"tts": tts, "mix": mix}[sys.argv[1] if len(sys.argv) > 1 else "tts"](*sys.argv[2:3])
