// Signal & Power Integrity Lab — every formula and number on the page next to its public source.
// The 參數依據 panel reads this file, and make_refs.py copies it into si/README.md.
window.SI_SOURCES = {
  intro: '這一頁用的是教科書等級的一階公式，目的是看出趨勢，不是取代模擬軟體。下面列出用到的公式、每個參數的預設值、公開資料裡的數字和出處。所有來源都是公開文件；數字是業界通用量級，不是任何產品或專案的規格。',
  dis: '測試載板和探針卡主板就是又厚、層數又多的 PCB：訊號要穿過整個板厚，幾百到上千安培的電流也要靠它送到晶片。背鑽、板材、疊構和電源層的安排，都是做板子的人要處理的事。',
  steps: [
    { zh: '殘樁共振', d: 'f = c ÷（4 × 殘樁長度 × √Dk）。開路的殘樁在四分之一波長時把訊號反相送回來，剛好抵消。這一頁把 Dk 乘上 1.69，因為實測的導通孔「看起來」的 Dk 比板材標示值高（實例 6.16 對 3.65）。', r: [1, 2] },
    { zh: '殘樁多長算太長', d: '經驗法則：殘樁要短於 300 mil ÷ 速率（Gb/s）。32 Gb/s 大約是 9 mil（0.24 mm）。超過 15 mil 的殘樁建議背鑽。', r: [3, 4, 5] },
    { zh: '走線損耗', d: '每英吋損耗（dB）≈ 31.6 × √f ÷（Z × (線寬 + 銅厚)）+ 2.32 × √Dk × Df × f，f 為 GHz、尺寸為 mil。前一項是銅的集膚效應，後一項是板材。粗糙銅面大約讓銅的損耗加倍。', r: [5, 6, 7] },
    { zh: '眼圖', d: '把一串隨機資料通過這條通道（損耗加兩個殘樁），每個位元疊在一起畫出來。眼高和眼寬取最佳取樣點附近的開口。PAM4 有三個眼，每個最多只有 NRZ 的三分之一。', r: [8, 9] },
    { zh: '不等化能撐多少', d: '經驗法則：NRZ 在 Nyquist 頻率損耗約 10 dB 以內不用等化；加上接收端等化後可以到 15–25 dB。', r: [10] },
    { zh: '目標阻抗', d: 'Z 目標 = 電壓 × 容許漣波 ÷ 電流跳升量，電流跳升量取最大電流的一半。電源路徑的阻抗要在整個頻段都低於它。', r: [17, 18, 19] },
    { zh: '電容的自振頻率', d: 'f = 1 ÷（2π√(LC)）。高於這個頻率，電容只剩電感的作用；所以要很多顆並聯，用不同容值由快到慢接力。', r: [15, 18] },
    { zh: '電壓下陷', d: 'ΔV = ΔI × Z。電流一跳，先由晶片和封裝裡的電容撐住，再來是板上的高頻、中、大電容，最後才是測試機電源。', r: [18, 22] },
    { zh: '直流壓降與遠端感測', d: '1 oz 銅箔每平方 0.5 mΩ，2 oz 是 0.25 mΩ；多層並聯就除以層數。測試機電源用另一組感測線量測待測端的電壓，把路徑上的壓降補回來，但只補得到它反應得過來的頻率。', r: [23, 24, 25] },
  ],
  params: [
    { p: '板厚', sim: '2.0–8.0 mm，預設 6.4 mm', real: '測試載板一般厚 0.200–0.300 英吋（5–7.6 mm）；公開例子為 4.8–7.6 mm、26–60 層', r: [11, 12] },
    { p: '背鑽後的殘樁', sim: '0.15 mm', real: '測試載板廠的規格是 0.15 ± 0.1 mm；一般板廠是 7 ± 5 mil（約 0.18 mm）', r: [12, 13] },
    { p: '走線長度', sim: '2–50 cm，預設 25 cm', real: '測試載板上的高速線常有 25–50 cm', r: [14] },
    { p: '線寬', sim: '4–20 mil，預設 6 mil', real: '高速板材上一般是 5–7 mil；測試載板也有用到 19 mil 的寬線來降低銅損', r: [11, 14] },
    { p: '差動阻抗', sim: '100 Ω（只用來算銅損）', real: '一般是 85–100 Ω，容許 ±10%；測試板廠標示可做到 ±5%', r: [15, 16, 5] },
    { p: '板材', sim: 'FR-4（Dk 3.92、Df 0.025）、N4000-13 SI（3.2、0.008）、Megtron 6（3.62、0.0046）、I-Tera MT40（3.45、0.0031）、Megtron 7（3.31、0.0023）、Tachyon 100G（3.02、0.0021）', real: '都是原廠規格書在 10–14 GHz 的典型值。各家量測方法不同，不能直接比大小。公開的測試載板例子用的是 I-Tera、Meteorwave 2000 和 FR-4', r: [26, 27, 28, 29, 30, 31, 12] },
    { p: '每英吋損耗（檢查用）', sim: '16 GHz：FR-4 約 2.0 dB、Megtron 6 約 0.49 dB（6 mil 線、平滑銅面）', real: '公開表格在 16 GHz 為 FR-4 1.29–1.84 dB、Megtron 6 0.34 dB（該表用的 Df 比規格書低）；經驗法則是 FR-4 每英吋每 GHz 0.2 dB、低損耗板材 0.1 dB', r: [5, 6] },
    { p: '訊號速率', sim: 'PCIe 3.0／4.0／5.0／6.0 和 112G', real: 'Nyquist 頻率為 4／8／16／16／28 GHz；整條通道的損耗上限為 22／28／36／32 dB 和 28–30 dB。PCIe 6.0 和 112G 用 PAM4', r: [32, 33, 34, 9] },
    { p: '接收端等化', sim: '一個零點一個極點的 CTLE，最多補 12 dB（示意）', real: '實際的接收端還有 FFE 和 DFE，合起來大約可以補到 25 dB', r: [10] },
    { p: '測試板上的訊號速度', sim: '—', real: '公開資料提到測試載板上有 112 Gb/s PAM4 的迴路測試，訊號從板子底面進來、從頂面的測試座出去，每條線都要穿過好幾個導通孔', r: [11] },
    { p: '電壓與容許漣波', sim: '0.6／0.8／1.0 V，±2／3／5%', real: '核心電壓約 1 V 以下，並往 0.75、0.6、0.5 V 走。容許範圍的公開例子：核心電源 ±5%、類比電源 ±3%，也有 2–2.5% 的', r: [35, 36, 17, 15, 19] },
    { p: '最大電流', sim: '20–1540 A，預設 200 A', real: '高效能運算晶片需要 1,000–1,500 A；測試機單張電源卡可供 640 A，可以並聯', r: [35, 37] },
    { p: '電容', sim: '大 470 μF（25 mΩ、2.5 nH）、中 47 μF（10 mΩ、1.6 nH）、高頻 0.47 μF（10 mΩ、1.0 nH），電感含安裝', r: [15, 20], real: '規格例：330–680 μF 鉭質電容 ESR 5–40 mΩ、ESL 1–2 nH；47–100 μF 陶瓷 ESR 1–40 mΩ、ESL 1 nH 以內；0.47 μF 陶瓷 ESR 1–20 mΩ、ESL 0.5 nH 以內。安裝另外加 0.3–4 nH；實測一顆 0402 的安裝電感約 0.52 nH' },
    { p: '電源接腳', sim: '每對 4 nH、30 mΩ（導通孔加測試座探針），20–5000 對並聯', real: '測試載板上，通到待測物的導通孔通常是電源路徑裡電感最大的一段；1.5 mm 厚的板子，導通孔約 0.3–1.5 nH，板子越厚越大。高效能晶片有上萬個電源和接地接點', r: [22, 15, 35] },
    { p: '電源層', sim: '2 oz 銅、每對 100 平方英吋，1–24 對；路徑算兩個正方形長', real: '4 mil 間距的電源層每平方英吋約 225 pF。公開的案例用 2 oz 銅和多層電源層，2.4 kW 的晶片在板上發熱 83 W、不到 3.5%', r: [15, 22] },
    { p: '遠端感測', sim: '感測點可選：無、板上、晶片端；約 100 kHz 以下有效（示意）。測試機電源每 20 A 一個通道並聯', real: '測試機的元件電源用四線式連接：兩條送電、兩條量電壓。穩壓器只在幾十到幾百 kHz 以下有低阻抗', r: [24, 25, 18] },
    { p: '封裝與晶片裡的電容', sim: '每安培 1 μF（示意）', real: '封裝內的電容規格例：0.47–4.7 μF、電感 60–110 pH。晶片和封裝的電容負責板上電容來不及反應的頻段，這一段不是板子能改的', r: [15, 18] },
    { p: '電流上升時間', sim: '1 ns–10 μs，預設 100 ns', real: '晶片內部的第一次下陷發生在 50–200 MHz；掃描測試時電流會在單一測試裡劇烈變化', r: [21, 35] },
  ],
  left: '沒有模擬的部分：串音、阻抗不連續造成的反射（除了殘樁）、連接器和測試座、抖動、FFE／DFE 等化、電源層的共振、電容擺放位置、溫度，以及封裝內部的細節。眼圖和電源阻抗都是用集總或一維模型算的，數字只代表趨勢。',
  refs: [
    { t: 'Simonovich — Via Stubs Demystified, 2017', u: 'https://blog.lamsimenterprises.com/2017/03/08/via-stubs-demystified/' },
    { t: 'Bogatin — The quarter-wave stub frequency: Rule of Thumb #17, EDN 2014', u: 'https://www.edn.com/the-quarter-wave-stub-frequency-rule-of-thumb-17/' },
    { t: 'Telian — Fixing the Problem of Stubs, Signal Integrity Journal 2023', u: 'https://www.signalintegrityjournal.com/articles/2962-fixing-the-problem-of-stubs' },
    { t: "Simonovich — The Poor Man's PCB Via Modeling Methodology, 2011", u: 'https://blog.lamsimenterprises.com/2011/03/14/the-poor-mans-pcb-via-modeling-methodology/' },
    { t: 'Texas Instruments — High-Speed PCB Layout for PCIe Gen 5, SNLA426, 2023', u: 'https://www.ti.com/lit/pdf/snla426' },
    { t: 'Bogatin — Loss in a channel: Rule of Thumb #9, EDN 2014', u: 'https://www.edn.com/loss-in-a-channel-rule-of-thumb-9/' },
    { t: 'Bogatin — How to Reduce Attenuation in a Differential Channel, Signal Integrity Journal 2020', u: 'https://www.signalintegrityjournal.com/articles/1734-how-to-reduce-attenuation-in-a-differential-channel' },
    { t: 'Keysight — Analyzing Data using Eye Diagrams', u: 'https://helpfiles.keysight.com/csg/N1930xB/Analyzing/Analyzing_Data_using_Eye_Diagrams.html' },
    { t: 'Intel/Altera — AN 835: PAM4 Signaling Fundamentals', u: 'https://docs.altera.com/r/docs/683852/current/an-835-pam4-signaling-fundamentals' },
    { t: 'Bogatin — How much attenuation is too much?: Rule of Thumb #10, EDN 2014', u: 'https://www.edn.com/how-much-attenuation-is-too-much-rule-of-thumb-10/' },
    { t: 'Armstrong & Thompson (Advantest) — HSIO Loopback Turns Challenges Into Opportunities For Test At 112 Gbps, SemiEngineering 2021', u: 'https://semiengineering.com/hsio-loopback-turns-challenges-into-opportunities-for-test-at-112-gbps/' },
    { t: 'TSE — Load board line-up and capability', u: 'https://www.tse21.com/eng/product/interfaceboard_loadboard.html' },
    { t: 'TTM Technologies — Back Drill Design Guideline, 2023', u: 'https://www.ttm.com/sites/default/files/documents/BackDrilling_TechBulletin.pdf' },
    { t: 'Moreira & Barnes (Verigy) — Choosing the Dielectric Material for a V93000 DUT Loadboard, 2008', u: 'https://www3.advantest.com/documents/11348/08232f5c-6d6f-4920-b7d8-4c683a098bb5' },
    { t: 'Xilinx — 7 Series FPGAs PCB Design Guide, UG483', u: 'https://docs.amd.com/v/u/en-US/ug483_7Series_PCB' },
    { t: 'Hemeixin — ATE PCB boards', u: 'https://www.hemeixinpcb.com/rigid-pcb/ate-pcb-boards.html' },
    { t: 'Altera — Device-Specific Power Delivery Network (PDN) Tool User Guide, 2014', u: 'https://docs.altera.com/v/u/docs/654614/device-specific-power-delivery-network-pdn-tool-user-guide' },
    { t: 'Altera — AN 574: PCB Power Delivery Network (PDN) Design Methodology, 2009', u: 'https://docs.altera.com/v/u/docs/654973/an-574-printed-circuit-board-pcb-power-delivery-network-pdn-design-methodology' },
    { t: 'Texas Instruments — Sitara Processor Power Distribution Networks: Implementation and Analysis, SPRAC76', u: 'https://www.ti.com/lit/an/sprac76h/sprac76h.pdf' },
    { t: 'McCaffrey, Huddleston, Dannan & Kuszewski — Who Put That Inductor in My Capacitor?, Signal Integrity Journal 2024', u: 'https://www.signalintegrityjournal.com/articles/3445-who-put-that-inductor-in-my-capacitor' },
    { t: 'Kim et al. (UT Austin / AMD) — AUDIT: Stress Testing the Automatic Way, MICRO 2012', u: 'https://lca.ece.utexas.edu/pubs/young_micro12.pdf' },
    { t: 'Furniturewala (R&D Altanova / Advantest) — Design Considerations For Ultra-High Current Power Delivery Networks, SemiEngineering 2023', u: 'https://semiengineering.com/design-considerations-for-ultra-high-current-power-delivery-networks/' },
    { t: 'Bogatin — Sheet resistance of copper foil: Rule of Thumb #13, EDN 2014', u: 'https://www.edn.com/sheet-resistance-of-copper-foil-rule-of-thumb-13/' },
    { t: 'Evaluation Engineering — Applying Kelvin Measurements To PMIC Testing on ATE, 2007', u: 'https://www.electronicdesign.com/technologies/test-measurement/article/21201453/applying-kelvin-measurements-to-pmic-testing-on-ate' },
    { t: 'EESemi — ATE Load Boards / DUT Boards / Interface Boards', u: 'https://www.eesemi.com/loadbrds.htm' },
    { t: 'Isola — 370HR data sheet', u: 'https://www.isola-group.com/wp-content/uploads/data-sheets/370hr.pdf' },
    { t: 'AGC — N4000-13 SI technical data sheet', u: 'https://www.agc-multimaterial.com/agc-downloads/AGC_N4000-13SI_TDS.pdf' },
    { t: 'Panasonic — MEGTRON 6 data sheet', u: 'https://industrial.panasonic.com/content/data/EM/PDF/DataS_MEGTRON6_R-5775_en_202410.pdf' },
    { t: 'Isola — I-Tera MT40 data sheet', u: 'https://www.isola-group.com/wp-content/uploads/data-sheets/i-tera-mt40.pdf' },
    { t: 'Panasonic — MEGTRON 7 data sheet', u: 'https://industrial.panasonic.com/content/data/EM/PDF/DataS_MEGTRON7_R-5785_en_2022.pdf' },
    { t: 'Isola — Tachyon 100G data sheet', u: 'https://www.isola-group.com/wp-content/uploads/data-sheets/tachyon-100g-laminate-and-prepreg.pdf' },
    { t: 'Astera Labs — PCI Express 5.0 Architecture Channel Insertion Loss Budget', u: 'https://www.asteralabs.com/pci-express-5-0-architecture-channel-insertion-loss-budget/' },
    { t: 'Krooswyk, Fellbaum & Burns (Samtec) — How To Choose an Interconnect for PCIe 6.0 High-Speed Systems, Signal Integrity Journal 2023', u: 'https://www.signalintegrityjournal.com/articles/2964-how-to-choose-an-interconnect-for-pcie-60-high-speed-systems' },
    { t: 'OIF — CEI Interoperability Demo at OFC 2024', u: 'https://www.oiforum.com/wp-content/uploads/OIF_CEI_Demo_OFC2024_Final.pdf' },
    { t: 'SemiEngineering — Delivering On Power During HPC Test, 2024', u: 'https://semiengineering.com/delivering-on-power-during-hpc-test/' },
    { t: 'Leventhal (Advantest) — AI Semiconductors Require An Integrated Test Solution, SemiEngineering 2025', u: 'https://semiengineering.com/ai-semiconductors-require-an-integrated-test-solution/' },
    { t: 'Advantest — DC Scale XHC32 ultra-high-current power supply, news release 2024', u: 'https://www.advantest.com/en/news/2024/20240515.html' },
  ],
};
