// MLO Lab — every number on the page next to its public source.
// The 參數依據 panel reads this file, and make_refs.py copies it into mlo/README.md.
window.MLO_SOURCES = {
  intro: '這是示意模型：幾何尺寸有放大，物理是一階公式。下面列出 MLO 的製程、每個參數用的值、公開資料裡的數字和出處。所有來源都是公開文件；數字是業界通用量級，不是任何產品或專案的規格。',
  dis: 'DIS Tech 官網寫到，它有設計、模擬和整合 MLO 空間轉換板的經驗，MLO 能讓多站同測的探針卡有良好的下針效率；同一頁也寫到可支援的元件接點間距小到 60 μm。',
  steps: [
    { zh: '核心板', d: '核心板先鑽孔、電鍍通孔，再做出兩面的線路。核心板本身也可以是多層板（例如中間 18 層、30 層）。', r: [20, 24, 3, 5] },
    { zh: '壓合增層膜', d: '把增層膜真空壓合在核心板兩面，最後的壓合溫度 160–180 °C，再以 180–190 °C 熟化約 90 分鐘。增層膜沒有玻纖布，雷射比較好鑽。', r: [21, 13] },
    { zh: '雷射鑽孔', d: '用 CO2 或 UV 雷射鑽出盲孔，停在下一層的銅墊上；40 μm 以下的孔要用 UV 雷射。', r: [20] },
    { zh: '除膠渣', d: '用過錳酸鹽把孔底的殘膠清掉，順便把表面咬粗，讓銅抓得住。', r: [13, 22] },
    { zh: '化學銅', d: '整面長一層 0.25–1 μm 的化學銅，當作電鍍的晶種。', r: [35, 22] },
    { zh: '光阻與曝光', d: '貼乾膜光阻、曝光顯影，只露出要長線路的地方；細線路常用雷射直接成像。', r: [20, 23] },
    { zh: '電鍍銅', d: '圖形電鍍把線路長到約 18–20 μm，同時把微孔填滿。', r: [23] },
    { zh: '去光阻、快速蝕刻', d: '去掉光阻，再把露出來的薄晶種銅蝕刻掉（約 2–3 μm），線路就分開了。每一層重複一次，孔可以一層一層疊上去。', r: [22, 23, 24] },
    { zh: '收尾與檢查', d: '防焊、表面處理（例如化鎳鈀浸金：鎳 3–6 μm、鈀 0.05–0.30 μm、金 0.03–0.07 μm）、電性測試、量翹曲。探針接觸的接點會鍍鎳金。', r: [34, 2, 25] },
  ],
  params: [
    { p: '探針側間距', sim: '40–200 μm，預設 80 μm', real: '公開路線圖：80 μm 為主流、45 μm 已開發、30 μm 開發中；公開的探針卡最小到 40 μm', r: [3, 32, 30] },
    { p: '主板側間距', sim: '1.0 mm', real: '2002 年的 MLO 錫球間距由 1.27 mm 走向 1.0、0.8、0.6 mm；也有 250 μm 轉到 1000 μm 的例子', r: [2, 5] },
    { p: '線寬／線距', sim: '5–30 μm，預設 12 μm', real: '公開的分級：SAP 30/30、20/20 μm，薄膜重佈線 5/5 μm；封裝載板量產約 10/10 μm，目標 5/5 μm', r: [4, 22, 24] },
    { p: '孔墊直徑', sim: '20–80 μm，預設 30 μm', real: 'CO2 雷射孔 25 μm 配孔墊 50 μm；UV 雷射孔 15 μm 配孔墊 30 μm。80 μm 間距的探針卡載板：雷射孔 40 μm、增層厚 30 μm', r: [4, 3] },
    { p: '走線規則', sim: '兩個孔墊之間可走 n 條線，n = ⌊(間距 − 孔墊 − 線距) ÷ (線寬 + 線距)⌋；每層拉出 n + 1 排（示意）', real: '公開表格的數字符合這條規則：不走線時最小間距 = 孔墊 + 線距；走一條線 = 孔墊 + 線寬 + 2 × 線距。BGA 外圈兩排可以直接在表層拉出，往內每多一層訊號層再拉出兩排', r: [4, 29] },
    { p: '層數', sim: '上下各 2–12 層，預設 6+核心+6', real: '公開的演進：6-2-6（2006）→ 7-24-7（2015）→ 20-18-20（2024），中間的數字是核心層數；也有 12+30+12 的寫法', r: [3, 5] },
    { p: '厚度', sim: '增層膜 30 μm、每層銅 15 μm（示意）、核心 1.4 mm；6+核心+6 約 2.0 mm', real: '空間轉換板一般 0.5–3 mm；公開的 100 × 100 mm 測試載板厚 3 mm，傳統核心 1.4 mm', r: [10, 3] },
    { p: '材料（一般）', sim: '增層膜 39 ppm／5 GPa、核心 14 ppm／26.5 GPa、銅 16.5 ppm／130 GPa', real: '公開的探針卡載板材料；增層膜例：GX92 為 39 ppm、5 GPa；純銅手冊值 16.9 ppm、約 117 GPa', r: [3, 13, 18] },
    { p: '材料（低膨脹）', sim: '增層膜 20 ppm／13 GPa、核心 6 ppm／34 GPa', real: '公開的低膨脹組；增層膜例：GL 為 20 ppm、13 GPa。公開的核心板材從 14 ppm 到 0.5 ppm 都有', r: [3, 13, 15, 16] },
    { p: '整片的熱膨脹係數', sim: '用層疊理論算：一般組約 15.7 ppm/K、低膨脹組約 9.7 ppm/K', real: '公開實測：1.4 mm 核心的整片約 15.5 ppm/K，2.0 mm 核心約 12.5 ppm/K', r: [3, 27] },
    { p: '陶瓷 MLC', sim: '3.4 ppm/K', real: '低溫共燒陶瓷 3.4 ppm/K；氧化鋁 7.1；探針卡用陶瓷 4.7；另一家 3.6–4.4。2002 年的例子：訂製陶瓷要等三個月、貴上百倍；2025 年的公開簡報把多層有機列為探針載板的首選', r: [17, 36, 7, 2, 31] },
    { p: '矽', sim: '2.6 ppm/K', real: '2.6 × 10⁻⁶ /°C', r: [19] },
    { p: '探針偏移', sim: '偏移 = (載板 − 矽) 的熱膨脹係數差 × 溫差 × 離中心距離；預設最遠 25 mm', real: '公開實測：25 → 150 °C，離中心 25 mm 處接點移動 48 μm（15.5 ppm）、39 μm（12.5 ppm）。實際載板比晶圓涼（實測約 86 °C 對 150 °C），本頁假設同溫，會高估', r: [3, 6] },
    { p: '容許偏移', sim: '±12.5 μm', real: '公開的針痕位置檢查上限：常溫 ±7.5 μm，高溫或低溫 ±12.5 μm', r: [8] },
    { p: '依測試溫度縮放', sim: '探針圖案照 125 °C 縮放', real: '把常溫的探針間距先縮放，讓它在測試溫度剛好對上；代價是每個溫度要一套', r: [12, 3] },
    { p: '測試溫度', sim: '−40–150 °C', real: '高溫 125–200 °C、低溫 −40 到 −55 °C；也有 −40 / 150 °C 的例子', r: [9, 37] },
    { p: '翹曲', sim: '層疊理論算曲率，弓高 = 曲率 × 長度² ÷ 8；以 180 °C 為無應力溫度，長度 100 mm', real: '銅量不平衡、疊構不對稱、材料之間熱膨脹不匹配都會造成翹曲；100 mm 載板例：約 +90 μm（室溫）、−100 μm（240 °C）', r: [27, 28, 26, 33, 14] },
    { p: '平整度上限', sim: '38 μm', real: '2002 年公開例子：整片 ≤ 0.0015 吋（38 μm）、探針區 ≤ 0.0005 吋（13 μm）；有機載板焊上後翹 60–70 μm，可銑平到 5 μm 以內', r: [2, 11] },
    { p: '與上下的連接', sim: '上面：探針壓在接點上；下面：錫球焊到主板', real: '垂直探針壓在載板上方的接點（不焊）；下方錫球迴焊到主板再加底部填膠，也有用轉接板或機構固定的', r: [10, 2, 1] },
  ],
  left: '沒有模擬的部分：核心板內部的多層線路、電性（阻抗、損耗、電源）、內嵌電容、疊孔的可靠度、玻璃核心與薄膜重佈線、載板和晶圓溫度不同（實際載板較涼），以及厚度方向的膨脹。走線用的是「每層拉出 n + 1 排」的簡化規則；實際 45 μm 以下的間距，孔墊之間已經放不下線，要靠孔中孔一路往下、在較深的層再展開。',
  refs: [
    { t: 'Chan & Leung (Intel) — C4 Probe Card Space Transformer Technology Overview, SWTW 2000', u: 'https://www.swtest.org/swtw_library/2000proc/PDF/S04_Chan.pdf' },
    { t: 'Fulton & Pardee (Wentworth Laboratories) — Using MLOs to Build Vertical Technology Space Transformers, SWTW 2002', u: 'https://www.swtest.org/swtw_library/2002proc/PDF/S04_03.pdf' },
    { t: 'Nozaka (FICT) — Space Transformer Organic Technologies for Next-Generation Probe Card Substrates, SWTest Asia 2024', u: 'https://www.swtestasia.org/2024proc/pdf/F06_01_NOZAKA_SWTestAsia2024.pdf' },
    { t: 'Yang (Princo Test) — An introduction for novel multi-layer thin film substrates applied in space transformers, SWTW 2018', u: 'http://www.swtest.org/swtw_library/2018proc/PDF/S09_02_Yang_SWTW2018.pdf' },
    { t: 'Furniturewala (R&D Altanova / Advantest) — Embedded Capacitors on the MLO for SerDes and PCIe loopback, SWTest 2023', u: 'https://www.swtest.org/library/2023proc/pdf/M01_03_Furniturewala_2023.pdf' },
    { t: 'Huang, Daly & Tai (Chunghwa Precision Test Tech.) — Thermal Challenges in the Fine Pitch Testing Solutions, SWTest 2023', u: 'https://www.swtest.org/library/2023proc/pdf/W08_03_Daly_2023.pdf' },
    { t: 'Cho et al. (SEMCNS) — Importance of Ceramic Substrates with Low Thermal Expansion Coefficient in Semiconductor Wafer Testing, SWTest 2023', u: 'https://www.swtest.org/library/2023proc/pdf/P01_05_In_SWTest_2023.pdf' },
    { t: 'Van Cauwenberghe (ON Semiconductor) — Wafer Probe Challenges for the Automotive Market, SWTW 2012', u: 'https://www.swtest.org/swtw_library/2012proc/PDF/S01_03_Cauwenberghe_SWTW2012.pdf' },
    { t: 'Sinsheimer & Buckholtz (Teradyne) — Wafer Sort at Extreme Temperatures, SWTW 2018', u: 'https://www.swtest.org/swtw_library/2018proc/PDF/P01_02_Buckholtz_SWTW2018.pdf' },
    { t: 'US11209463B2 (Technoprobe) — Probe card for a testing apparatus', u: 'https://patents.google.com/patent/US11209463B2/en' },
    { t: 'US10288645B2 — organic laminate probe substrate flattened before probe formation', u: 'https://patents.google.com/patent/US10288645B2/en' },
    { t: 'EP1356307A1 (Wentworth) — probe pitch compensated for the test temperature', u: 'https://patents.google.com/patent/EP1356307A1/en' },
    { t: 'Tatsumi, Fujishima & Sakauchi (Ajinomoto) — Advanced Build-up Materials for High Speed Transmission Application, IMAPS 2018', u: 'https://imapsource.scholasticahq.com/api/v1/articles/55935-advanced-build-up-materials-for-high-speed-transmission-application.pdf' },
    { t: 'Mitsukura (Resonac) & Hisada (Rapidus) — Trend of Organic Substrate Materials, IEEE EPS', u: 'https://eps.ieee.org/wp-content/uploads/2025/11/Trend_of_Organic_Substrate_Materials_Article__mitsukura_hisada.pdf' },
    { t: 'Resonac — MCL catalog 2023–2024 (core laminates)', u: 'https://www.resonac.com/sites/default/files/2024-07/2023-2024MCL_catalog_EN.pdf' },
    { t: 'Mitsubishi Gas Chemical — BT laminate lineup', u: 'https://www.mgc.co.jp/eng/products/sc/btprint/lineup/hfbt.html' },
    { t: 'Kyocera — fine ceramic material properties', u: 'https://global.kyocera.com/prdct/semicon/material/' },
    { t: 'Copper Development Association — C11000 properties', u: 'https://alloys.copper.org/alloy/C11000' },
    { t: 'Ioffe Institute — Silicon thermal properties', u: 'https://www.ioffe.ru/SVA/NSM/Semicond/Si/thermal.html' },
    { t: 'KLA — IC Substrates Part II: Six Yield-Critical Challenges for Manufacturers', u: 'https://www.kla.com/advance/innovation/ic-substrates-part-ii-six-yield-critical-challenges-for-manufacturers' },
    { t: 'Polymer Innovation Blog — Build-up films for flip-chip substrates, part one', u: 'https://polymerinnovationblog.com/polymers-in-electronic-packaging-build-up-films-for-flip-chip-semiconductor-substrates-part-one/' },
    { t: 'Kawashima & Tajima (Meltex) — Advanced Chemical Processes for Semi-additive PWB Fabrication, Line and Space 5 µm, IMAPS 2015', u: 'https://imapsource.org/api/v1/articles/57213-advanced-chemical-processes-for-semi-additive-pwb-fabrication-for-fine-line-formation-targeting-line-and-space-5-m-5-m.pdf' },
    { t: 'Bellemare & Kologe — Semiadditive Processing, PCD&F', u: 'https://www.pcdandf.com/pcdesign/index.php/editorial/menu-features/13128-semiadditive-processing-1811' },
    { t: 'Toppan — FC-BGA substrates', u: 'https://www.toppan.com/en/electronics/package/fc-bga/' },
    { t: 'JEITA ED-7306 — Measurement methods of package warpage at elevated temperature and the maximum permissible warpage', u: 'https://home.jeita.or.jp/tsc/std-pdf/ED-7306_E.pdf' },
    { t: 'Sierra Circuits — Balanced copper distribution and copper weight in PCBs', u: 'https://www.protoexpress.com/blog/balanced-copper-distribution-and-copper-weight-in-pcbs/' },
    { t: 'A summary of Classical Lamination Theory (course notes)', u: 'https://wstein.org/edu/2010/480b/projects/05-lamination_theory/A%20summary%20of%20Classical%20Lamination%20Theory.pdf' },
    { t: 'Wikipedia — Bimetallic strip (Timoshenko curvature)', u: 'https://en.wikipedia.org/wiki/Bimetallic_strip' },
    { t: 'Altium — How to successfully design a BGA', u: 'https://resources.altium.com/p/how-to-successfully-design-a-bga' },
    { t: 'DIS Tech — Our technologies', u: 'https://www.dis.tech/technologies-and-products/our-technologies' },
    { t: 'Technoprobe — Capital Markets Day 2025', u: 'https://www.technoprobe.com/wp-content/uploads/2025/04/Technoprobe-CMD2025.pdf' },
    { t: 'Technoprobe — What is a probe card', u: 'https://www.technoprobe.com/technologies-and-products/what-is-a-probe-card' },
    { t: 'Liu (Flextronics) — Challenges of Organic Substrates from EMS Perspective, iNEMI 2014', u: 'https://thor.inemi.org/webdownload/2014/Substrate_Pkg_WS_Apr/03_Flextronics.pdf' },
    { t: 'Milad — The IPC surface finish specifications, I-Connect007 2021', u: 'https://iconnect007.com/article/129297/the-plating-forum-the-ipc-surface-finish-specifications/129300/pcb' },
    { t: 'Peng et al. — Additive processing, PCD&F', u: 'https://pcdandf.com/pcdesign/index.php/editorial/menu-features/11588-additive-processing-1704' },
    { t: 'Kyocera — probe card ceramics ST300 (archived page)', u: 'http://web.archive.org/web/20250724022534/https://global.kyocera.com/prdct/semicon/search_application/detail/m_probecard.html' },
    { t: 'Dastmalchi, Harker (FormFactor) & Heitzer (Infineon) — Advancing Probe Card Parallelism for SOC Devices, SWTest 2022', u: 'https://www.swtest.org/library/2022proc/pdf/M03_03_Dastmalchi_SWTest_2022F.pdf' },
  ],
};
